"""Base template class for workflow script generation."""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any


@dataclass
class WorkflowTemplate(ABC):
    """Base class for workflow templates.

    Attributes
    ----------
    name : str
        Template name (e.g., "relax", "phonon")
    description : str
        Brief description of the workflow
    runtime_estimate : str
        Estimated runtime (e.g., "5-10 minutes")
    output_files : list[str]
        Expected output files from the workflow
    """

    name: str
    description: str
    runtime_estimate: str
    output_files: list[str]

    @abstractmethod
    def generate_imports(self, options: dict[str, Any]) -> str:
        """Generate import statements.

        Parameters
        ----------
        options : dict
            User-provided options

        Returns
        -------
        str
            Import statements
        """

    @abstractmethod
    def generate_maker(self, options: dict[str, Any]) -> str:
        """Generate maker initialization code.

        Parameters
        ----------
        options : dict
            User-provided options

        Returns
        -------
        str
            Maker initialization code
        """

    def generate_header(
        self, structure_path: str, command: str, options: dict[str, Any]
    ) -> str:
        """Generate script header with docstring.

        Parameters
        ----------
        structure_path : str
            Path to structure file
        command : str
            Original command used to generate the script
        options : dict
            User-provided options

        Returns
        -------
        str
            Header docstring
        """
        # Local wall-clock timestamp for the generated script header.
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")  # noqa: DTZ005

        header = f'''#!/usr/bin/env python
"""
{self.name.upper()} workflow

Generated by: atomate2siesta-maker
Date: {timestamp}
Command: {command}

Description:
{self.description}

Expected runtime: {self.runtime_estimate}
Output files:
'''
        for output_file in self.output_files:
            header += f"  - {output_file}\n"

        header += '"""\n'
        return header

    def generate_config_check(self, options: dict[str, Any]) -> str:
        """Generate configuration check section.

        Parameters
        ----------
        options : dict
            User-provided options

        Returns
        -------
        str
            Configuration check code
        """
        return """
# ============================================================================
# CONFIGURATION CHECK
# ============================================================================
import os
import sys
from atomate2.siesta import SETTINGS

pp_path = SETTINGS.SIESTA_PP_PATH or os.environ.get("SIESTA_PP_PATH")
if not pp_path:
    print("❌ ERROR: SIESTA_PP_PATH not configured!")
    print("Set it in ~/.atomate2siesta.yaml or as environment variable")
    sys.exit(1)

siesta_cmd = SETTINGS.SIESTA_CMD or os.environ.get("SIESTA_CMD", "siesta")
"""

    def generate_structure_loading(
        self, structure_path: str, options: dict[str, Any]
    ) -> str:
        """Generate structure loading code.

        Parameters
        ----------
        structure_path : str
            Path to structure file
        options : dict
            User-provided options

        Returns
        -------
        str
            Structure loading code
        """
        return f"""
# ============================================================================
# LOAD STRUCTURE
# ============================================================================
structure = Structure.from_file("{structure_path}")
print(f"Loaded: {{structure.composition.reduced_formula}}")
print(f"Space group: {{structure.get_space_group_info()}}")
print(f"Atoms: {{len(structure)}}")
"""

    def generate_database_setup(self, options: dict[str, Any]) -> str:
        """Generate database configuration code.

        Parameters
        ----------
        options : dict
            User-provided options

        Returns
        -------
        str
            Database setup code
        """
        db_config = options.get("db_config")

        if not db_config:
            return ""

        if db_config.get("method") == "jobflow_yaml":
            return """
# ============================================================================
# DATABASE CONFIGURATION
# ============================================================================
# Using ~/.jobflow.yaml for automatic database configuration
# Make sure ~/.jobflow.yaml exists with JOB_STORE configured
from pathlib import Path

jobflow_config = Path.home() / ".jobflow.yaml"
if not jobflow_config.exists():
    print("⚠ Warning: ~/.jobflow.yaml not found")
    print("Results will not be saved to database")
    print("Run: atomate2siesta-config create  # to create config file")
"""

        # Explicit JobStore configuration
        host = db_config.get("host", "localhost")
        port = db_config.get("port", 27017)
        database = db_config.get("database", "atomate2siesta")
        collection = db_config.get("collection", "tasks")

        return f"""
# ============================================================================
# DATABASE CONFIGURATION
# ============================================================================
from jobflow import SETTINGS, JobStore
from maggma.stores import MongoStore

# Define MongoDB store
store = MongoStore(
    database="{database}",
    collection_name="{collection}",
    host="{host}",
    port={port},
)

# Create JobStore and set in SETTINGS
job_store = JobStore(docs_store=store)
SETTINGS.JOB_STORE = job_store

print("✓ Database configured:")
print(f"  Host: {host}")
print(f"  Database: {database}")
print(f"  Collection: {collection}")
"""

    def generate_execution(self, options: dict[str, Any]) -> str:
        """Generate execution code.

        Parameters
        ----------
        options : dict
            User-provided options

        Returns
        -------
        str
            Execution code
        """
        dry_run = options.get("dry_run", False)
        remote = options.get("remote", False)

        if remote:
            return """
# ============================================================================
# SUBMIT TO REMOTE
# ============================================================================
from jobflow_remote import submit_flow

# Create workflow
flow = maker.make(structure)

# Submit to remote worker
response = submit_flow(flow, worker="{worker}")
print(f"✓ Submitted to remote worker: {{response}}")
""".format(worker=options.get("worker", "default"))

        if dry_run:
            return """
# ============================================================================
# RUN WORKFLOW (DRY-RUN MODE)
# ============================================================================
# Dry-run mode: Only generates input files, does not run calculations
flow = maker.make(structure)
results = run_locally(flow, create_folders=True, ensure_success=True)

print("\\n✓ Dry-run complete! Check output directories for generated input files.")
"""

        return """
# ============================================================================
# RUN WORKFLOW
# ============================================================================
flow = maker.make(structure)
results = run_locally(flow, create_folders=True, ensure_success=True)

print("\\n✓ Workflow complete!")
"""

    def generate_customization_section(self, options: dict[str, Any]) -> str:
        """Generate optional customization section with examples.

        Parameters
        ----------
        options : dict
            User-provided options

        Returns
        -------
        str
            Customization section with commented examples
        """
        return """
# ============================================================================
# OPTIONAL CUSTOMIZATION
# ============================================================================
# Uncomment and modify as needed:
# from atomate2.siesta.powerups import update_user_siesta_settings
# maker = update_user_siesta_settings(maker, {
#     "PAO.BasisSize": "DZP",
#     "kpts": [6, 6, 6],
#     "Mesh.Cutoff": "300 Ry",
# })
"""

    def generate_results_section(self, options: dict[str, Any]) -> str:
        """Generate results display section.

        Parameters
        ----------
        options : dict
            User-provided options

        Returns
        -------
        str
            Results section
        """
        return """
# ============================================================================
# OUTPUT FILES
# ============================================================================
print("\\nGenerated files:")
"""

    def generate(
        self, structure_path: str, command: str, options: dict[str, Any]
    ) -> str:
        """Generate complete workflow script.

        Parameters
        ----------
        structure_path : str
            Path to structure file
        command : str
            Original command used to generate script
        options : dict
            User-provided options

        Returns
        -------
        str
            Complete Python script
        """
        script = self.generate_header(structure_path, command, options)
        script += "\n"
        script += self.generate_imports(options)
        script += self.generate_config_check(options)
        script += self.generate_structure_loading(structure_path, options)
        script += self.generate_database_setup(options)
        script += "\n"
        script += self.generate_maker(options)
        script += self.generate_customization_section(options)
        script += self.generate_execution(options)
        script += self.generate_results_section(options)

        return script

    def validate_inputs(self, structure_path: str, options: dict[str, Any]) -> None:
        """Validate inputs before script generation.

        Parameters
        ----------
        structure_path : str
            Path to structure file
        options : dict
            User-provided options

        Raises
        ------
        FileNotFoundError
            If structure file doesn't exist
        ValueError
            If options are invalid
        """
        if not Path(structure_path).exists():
            raise FileNotFoundError(f"Structure file not found: {structure_path}")

        # Subclasses can add specific validation
        self._validate_specific(options)

    # Optional hook: subclasses may override; the base is intentionally a no-op.
    def _validate_specific(self, options: dict[str, Any]) -> None:  # noqa: B027
        """Template-specific validation (override in subclasses).

        Parameters
        ----------
        options : dict
            User-provided options
        """
