#!/usr/bin/env python
"""Read SIESTA FDF files using siesta_to_pymatgen powerup."""

from glob import glob
from jobflow import run_locally
from pymatgen.core import Structure
from atomate2.siesta.jobs.core import RelaxMaker
from atomate2.siesta.powerups import siesta_to_pymatgen

# First create a SIESTA calculation to get FDF files
structure = Structure.from_file("../../../00-structures/Si_mp-149_primitive.cif")
maker = RelaxMaker.fixed_cell_relaxation(dry_run=True)
job = maker.make(structure)
results = run_locally(job, create_folders=True)

# NOTE: dry_run creates files in job_*/dry_run_output/*/siesta.fdf
# XV files are only generated by actual SIESTA execution (dry_run=False)

# Find the dry_run output directory
fdf_pattern = "job_*/dry_run_output/*/siesta.fdf"
fdf_files = glob(fdf_pattern)
if fdf_files:
    fdf_path = fdf_files[0]
    print(f"Found FDF file: {fdf_path}")

    # Read from SIESTA FDF file
    structure_fdf = siesta_to_pymatgen(fdf_path, use_xv=False)
    print("✓ Read structure from siesta.fdf")

    # Convert to other formats
    structure_fdf.to(filename="from_fdf.cif", fmt="cif")
    structure_fdf.to(filename="from_fdf.xsf", fmt="xsf")
    print("✓ Converted FDF structure to CIF and XSF")
else:
    print("❌ No FDF file found")

# NOTE: To read XV files (relaxed geometries), run without dry_run:
# maker = RelaxMaker.fixed_cell_relaxation(dry_run=False)
# Then use: siesta_to_pymatgen("job_*/siesta.XV")
