safe:
 - pydantic
 - pymatgen
 - custodian
 - monty
 - jobflow
 - click
 - PyYAML
 - cclib
 - phonopy
 - seekpath
 - mp-api
 - dscribe
 - pymatgen-analysis-defects
 - numpydoc
 - ipython
 - FireWorks
 - autodoc_pydantic
 - jupyter-book
 - pytest
 - pytest-cov
 - FireWorks
 - pre-commit
 - numpy
 - click
 - jsonschema
