MULLIKEN and LOEWDIN POPULATION ANALYSIS

  atom#    atom      Mulliken charge       Loewdin charge
      1      Ga                 0.13                -0.07
      2      Ga                 0.13                -0.07
      3      Ga                 0.13                -0.07
      4      Ga                 0.13                -0.07
      5      As                -0.13                 0.07
      6      As                -0.13                 0.07
      7      As                -0.13                 0.07
      8      As                -0.13                 0.07

          total                -0.00                -0.00
