Electrostatic site potentials (in V) using Ewald splitting parameter 3.14
This first parameter is a default value that was determined by LOBSTER

  atom#    atom      Potential       Potential
                    (Mulliken)       (Loewdin)
      1      Ga          -1.26            0.70
      2      Ga          -1.27            0.70
      3      Ga          -1.26            0.70
      4      Ga          -1.27            0.70
      5      As           1.27           -0.70
      6      As           1.27           -0.70
      7      As           1.26           -0.70
      8      As           1.26           -0.70

Madelung Energy (eV)     -0.68           -0.21
