comment:
  layout: "diff, files"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes
coverage:
  status:
    project:
      default:
        only_pulls: true
    patch:
      default:
        only_pulls: true
