Mulliken and Loewdin gross orbital population

  atom#    atom   basisfunction     Mulliken GP      Loewdin GP
      1      Si             3s            1.26            1.08
                          3p_y            0.92            0.98
                          3p_z            0.92            0.98
                          3p_x            0.92            0.98
                         total            4.01            4.01

      2      Si             3s            1.26            1.08
                          3p_y            0.91            0.97
                          3p_z            0.91            0.97
                          3p_x            0.91            0.97
                         total            3.99            3.99
