"""Tests for jobflow-remote setup CLI tool.

This module tests the atomate2siesta-jobflow-remote command-line interface for
jobflow-remote installation and configuration.
"""

from __future__ import annotations

from unittest.mock import Mock, patch

import pytest
import yaml
from click.testing import CliRunner

from atomate2.siesta.cli.jobflow_remote.utils import (
    _backup_config,
    _get_comment,
    _get_comment_dict,
    _load_yaml_config,
    _save_yaml_config,
    _update_nested_dict,
)
from atomate2.siesta.cli.jobflow_remote import cli


class TestHelperFunctions:
    """Tests for helper functions."""

    def test_update_nested_dict_simple(self):
        """Test updating a simple nested dictionary."""
        base = {"a": 1, "b": {"c": 2}}
        update = {"b": {"c": 3, "d": 4}}

        result = _update_nested_dict(base, update)

        assert result["a"] == 1
        assert result["b"]["c"] == 3
        assert result["b"]["d"] == 4

    def test_update_nested_dict_deep(self):
        """Test updating a deeply nested dictionary."""
        base = {"a": {"b": {"c": 1}}}
        update = {"a": {"b": {"c": 2, "d": 3}}}

        result = _update_nested_dict(base, update)

        assert result["a"]["b"]["c"] == 2
        assert result["a"]["b"]["d"] == 3

    def test_update_nested_dict_overwrite_non_dict(self):
        """Test that non-dict values are overwritten."""
        base = {"a": 1}
        update = {"a": {"b": 2}}

        result = _update_nested_dict(base, update)

        assert result["a"] == {"b": 2}

    def test_load_yaml_config(self, tmp_path):
        """Test loading YAML configuration."""
        config_file = tmp_path / "config.yaml"
        config_data = {"key1": "value1", "key2": {"nested": "value2"}}

        with open(config_file, "w") as f:
            yaml.dump(config_data, f)

        loaded = _load_yaml_config(config_file)

        assert loaded == config_data

    def test_save_yaml_config(self, tmp_path):
        """Test saving YAML configuration."""
        config_file = tmp_path / "config.yaml"
        config_data = {"key1": "value1", "key2": {"nested": "value2"}}

        _save_yaml_config(config_file, config_data)

        with open(config_file) as f:
            loaded = yaml.safe_load(f)

        assert loaded == config_data

    def test_save_yaml_config_with_comments(self, tmp_path):
        """Test saving YAML configuration with comments."""
        config_file = tmp_path / "config.yaml"
        config_data = {"name": "test_project", "workers": {}}

        _save_yaml_config(config_file, config_data, add_comments=True)

        content = config_file.read_text()
        assert "# Jobflow Remote Configuration File" in content
        assert "# Generated by atomate2siesta-jobflow-remote" in content
        assert "name:" in content

    def test_backup_config(self, tmp_path):
        """Test creating a backup of configuration file."""
        config_file = tmp_path / "config.yaml"
        config_file.write_text("test content")

        backup_path = _backup_config(config_file)

        assert backup_path.exists()
        assert backup_path.read_text() == "test content"
        assert ".backup_" in backup_path.name

    def test_get_comment_dict_exact_match(self):
        """Test getting comment dict with exact path match."""
        comments = {"workers": {"local_worker": {"type": "Worker type comment"}}}

        result = _get_comment_dict(comments, ["workers", "local_worker"])

        assert result == {"type": "Worker type comment"}

    def test_get_comment_dict_wildcard_match(self):
        """Test getting comment dict with wildcard matching."""
        comments = {
            "workers": {"*": {"type": "Worker type comment", "host": "Host comment"}}
        }

        # Should match any worker name using wildcard
        result = _get_comment_dict(comments, ["workers", "some_worker"])

        assert result == {"type": "Worker type comment", "host": "Host comment"}

    def test_get_comment_dict_not_found(self):
        """Test getting comment dict for non-existent path."""
        comments = {"workers": {}}

        result = _get_comment_dict(comments, ["workers", "missing", "path"])

        assert result == {}

    def test_get_comment_exact_match(self):
        """Test getting comment with exact path match."""
        comments = {"queue": {"store": {"host": "MongoDB server hostname"}}}

        comment = _get_comment(comments, ["queue", "store", "host"])

        assert comment == "MongoDB server hostname"

    def test_get_comment_wildcard_match(self):
        """Test getting comment with wildcard matching."""
        comments = {"workers": {"*": {"type": "Worker type: 'local' or 'remote'"}}}

        comment = _get_comment(comments, ["workers", "any_worker", "type"])

        assert comment == "Worker type: 'local' or 'remote'"

    def test_get_comment_not_found(self):
        """Test getting comment for non-existent path."""
        comments = {"workers": {}}

        comment = _get_comment(comments, ["workers", "missing", "field"])

        assert comment == ""


class TestInstallCommand:
    """Tests for install command."""

    def setup_method(self):
        """Set up test fixtures."""
        self.runner = CliRunner()

    @patch("atomate2.siesta.cli.jobflow_remote.setup.subprocess.run")
    def test_install_stable(self, mock_run):
        """Test installing stable version."""
        mock_run.return_value = Mock(returncode=0)

        result = self.runner.invoke(cli, ["install"])

        assert result.exit_code == 0
        assert "Installation successful" in result.output
        # Check that pip install was called with correct package
        call_args = mock_run.call_args[0][0]
        assert "pip" in call_args
        assert "install" in call_args
        assert "jobflow-remote" in call_args

    @patch("atomate2.siesta.cli.jobflow_remote.setup.subprocess.run")
    def test_install_dev(self, mock_run):
        """Test installing development version."""
        mock_run.return_value = Mock(returncode=0)

        result = self.runner.invoke(cli, ["install", "--dev"])

        assert result.exit_code == 0
        assert "development version" in result.output
        # Check that GitHub URL was used
        call_args = mock_run.call_args[0][0]
        assert any("github.com" in str(arg) for arg in call_args)

    @patch("atomate2.siesta.cli.jobflow_remote.setup.subprocess.run")
    def test_install_failure(self, mock_run):
        """Test installation failure handling."""
        from subprocess import CalledProcessError

        mock_run.side_effect = CalledProcessError(
            1, "pip install", stderr="Installation failed"
        )

        result = self.runner.invoke(cli, ["install"])

        assert result.exit_code == 1
        assert "Installation failed" in result.output


class TestSetupCommand:
    """Tests for setup command."""

    def setup_method(self):
        """Set up test fixtures."""
        self.runner = CliRunner()

    def test_setup_generate_new_config(self, tmp_path):
        """Test generating new configuration file."""
        # Mock the config directory
        config_dir = tmp_path / ".jfremote"
        config_dir.mkdir()

        with patch(
            "atomate2.siesta.cli.jobflow_remote.setup.Path.home", return_value=tmp_path
        ):
            with patch(
                "atomate2.siesta.cli.jobflow_remote.setup.subprocess.run"
            ) as mock_run:
                mock_run.return_value = Mock(
                    returncode=0, stdout="Project generated", stderr=""
                )

                result = self.runner.invoke(cli, ["setup"])

                assert result.exit_code == 0
                # Config should have been generated

    def test_setup_update_nonexistent_config(self, tmp_path):
        """Test updating non-existent configuration file."""
        with patch(
            "atomate2.siesta.cli.jobflow_remote.setup.Path.home", return_value=tmp_path
        ):
            result = self.runner.invoke(cli, ["setup", "--update"])

            assert result.exit_code == 1
            assert "Configuration file not found" in result.output

    def test_setup_update_existing_config(self, tmp_path):
        """Test updating existing configuration file."""
        # Create config directory and file
        config_dir = tmp_path / ".jfremote"
        config_dir.mkdir()
        config_file = config_dir / "atomate2siesta.yaml"

        # Create minimal configuration
        config_data = {
            "name": "atomate2siesta",
            "queue": {"store": {"database": "olddb", "host": "oldhost", "port": 27017}},
            "jobstore": {
                "docs_store": {"database": "olddb", "host": "oldhost", "port": 27017}
            },
        }
        _save_yaml_config(config_file, config_data)

        with patch(
            "atomate2.siesta.cli.jobflow_remote.setup.Path.home", return_value=tmp_path
        ):
            result = self.runner.invoke(
                cli,
                [
                    "setup",
                    "--update",
                    "--database",
                    "newdb",
                    "--host",
                    "newhost",
                    "--port",
                    "27018",
                ],
            )

            assert result.exit_code == 0
            assert "Configuration updated successfully" in result.output

            # Verify configuration was updated
            updated_config = _load_yaml_config(config_file)
            assert updated_config["queue"]["store"]["database"] == "newdb"
            assert updated_config["queue"]["store"]["host"] == "newhost"
            assert updated_config["queue"]["store"]["port"] == 27018
            assert updated_config["jobstore"]["docs_store"]["database"] == "newdb"

    def test_setup_update_with_backup(self, tmp_path):
        """Test that backup is created when updating config."""
        # Create config directory and file
        config_dir = tmp_path / ".jfremote"
        config_dir.mkdir()
        config_file = config_dir / "atomate2siesta.yaml"

        config_data = {
            "name": "atomate2siesta",
            "queue": {
                "store": {"database": "olddb", "host": "localhost", "port": 27017}
            },
            "jobstore": {
                "docs_store": {"database": "olddb", "host": "localhost", "port": 27017}
            },
        }
        _save_yaml_config(config_file, config_data)

        with patch(
            "atomate2.siesta.cli.jobflow_remote.setup.Path.home", return_value=tmp_path
        ):
            result = self.runner.invoke(
                cli, ["setup", "--update", "--database", "newdb"]
            )

            assert result.exit_code == 0
            assert "Backup created" in result.output

            # Check that backup file exists
            backup_files = list(config_dir.glob("atomate2siesta.backup_*.yaml"))
            assert len(backup_files) == 1

    def test_setup_update_no_backup(self, tmp_path):
        """Test updating config without creating backup."""
        # Create config directory and file
        config_dir = tmp_path / ".jfremote"
        config_dir.mkdir()
        config_file = config_dir / "atomate2siesta.yaml"

        config_data = {
            "name": "atomate2siesta",
            "queue": {
                "store": {"database": "olddb", "host": "localhost", "port": 27017}
            },
            "jobstore": {
                "docs_store": {"database": "olddb", "host": "localhost", "port": 27017}
            },
        }
        _save_yaml_config(config_file, config_data)

        with patch(
            "atomate2.siesta.cli.jobflow_remote.setup.Path.home", return_value=tmp_path
        ):
            result = self.runner.invoke(
                cli, ["setup", "--update", "--no-backup", "--database", "newdb"]
            )

            assert result.exit_code == 0
            assert "Backup created" not in result.output

            # Check that no backup file exists
            backup_files = list(config_dir.glob("atomate2siesta.backup_*.yaml"))
            assert len(backup_files) == 0

    def test_setup_custom_project_name(self, tmp_path):
        """Test generating config with custom project name."""
        config_dir = tmp_path / ".jfremote"
        config_dir.mkdir()

        with patch(
            "atomate2.siesta.cli.jobflow_remote.setup.Path.home", return_value=tmp_path
        ):
            with patch(
                "atomate2.siesta.cli.jobflow_remote.setup.subprocess.run"
            ) as mock_run:
                mock_run.return_value = Mock(
                    returncode=0, stdout="Project generated", stderr=""
                )

                result = self.runner.invoke(
                    cli, ["setup", "--project-name", "my_project"]
                )

                assert result.exit_code == 0

    def test_setup_update_additional_stores(self, tmp_path):
        """Test that additional stores are also updated."""
        # Create config directory and file
        config_dir = tmp_path / ".jfremote"
        config_dir.mkdir()
        config_file = config_dir / "atomate2siesta.yaml"

        config_data = {
            "name": "atomate2siesta",
            "queue": {
                "store": {"database": "olddb", "host": "localhost", "port": 27017}
            },
            "jobstore": {
                "docs_store": {"database": "olddb", "host": "localhost", "port": 27017},
                "additional_stores": {
                    "data": {
                        "type": "GridFSStore",
                        "database": "olddb",
                        "host": "localhost",
                        "port": 27017,
                    }
                },
            },
        }
        _save_yaml_config(config_file, config_data)

        with patch(
            "atomate2.siesta.cli.jobflow_remote.setup.Path.home", return_value=tmp_path
        ):
            result = self.runner.invoke(
                cli, ["setup", "--update", "--database", "newdb", "--host", "newhost"]
            )

            assert result.exit_code == 0

            # Verify additional stores were updated
            updated_config = _load_yaml_config(config_file)
            assert (
                updated_config["jobstore"]["additional_stores"]["data"]["database"]
                == "newdb"
            )
            assert (
                updated_config["jobstore"]["additional_stores"]["data"]["host"]
                == "newhost"
            )


class TestInfoCommand:
    """Tests for info command."""

    def setup_method(self):
        """Set up test fixtures."""
        self.runner = CliRunner()

    def test_info_command(self):
        """Test info command displays expected information."""
        result = self.runner.invoke(cli, ["info"])

        assert result.exit_code == 0
        assert "Jobflow Remote" in result.output or "jobflow-remote" in result.output
        # Check for general structure elements
        assert "install" in result.output or "setup" in result.output


class TestTestCommand:
    """Tests for test command."""

    def setup_method(self):
        """Set up test fixtures."""
        self.runner = CliRunner()

    def test_test_command_no_config(self, tmp_path):
        """Test test command when no configuration exists (if it exists)."""
        # Check if test command exists, otherwise skip
        result = self.runner.invoke(cli, ["--help"])
        if "test" not in result.output:
            pytest.skip("test command not implemented in CLI")

        with patch(
            "atomate2.siesta.cli.jobflow_remote.setup.Path.home", return_value=tmp_path
        ):
            result = self.runner.invoke(cli, ["test"])

            # Either exit code 1 or 2 (missing option) is acceptable
            assert result.exit_code != 0

    def test_test_command_with_config(self, tmp_path):
        """Test test command with valid configuration (if it exists)."""
        # Check if test command exists, otherwise skip
        result_help = self.runner.invoke(cli, ["--help"])
        if "test" not in result_help.output:
            pytest.skip("test command not implemented in CLI")

        # Create config directory and file
        config_dir = tmp_path / ".jfremote"
        config_dir.mkdir()
        config_file = config_dir / "atomate2siesta.yaml"

        config_data = {
            "name": "atomate2siesta",
            "workers": {"local_shell": {"type": "local", "scheduler_type": "shell"}},
        }
        _save_yaml_config(config_file, config_data)

        with patch(
            "atomate2.siesta.cli.jobflow_remote.setup.Path.home", return_value=tmp_path
        ):
            with patch(
                "atomate2.siesta.cli.jobflow_remote.setup.subprocess.run"
            ) as mock_run:
                # Mock successful job submission
                mock_run.return_value = Mock(
                    returncode=0, stdout="Job submitted: test-job-uuid", stderr=""
                )

                result = self.runner.invoke(cli, ["test"])

                # Either the command works or it's not fully implemented
                # We just check it doesn't crash
                assert result.exit_code in [0, 1, 2]


class TestRunnerCommand:
    """Tests for runner command."""

    def setup_method(self):
        """Set up test fixtures."""
        self.runner = CliRunner()

    def test_runner_command(self):
        """Test runner command displays management information."""
        result = self.runner.invoke(cli, ["runner"])

        assert result.exit_code == 0
        assert "Runner Management" in result.output
        assert "Commands" in result.output or "runner" in result.output.lower()
