"""Workflows for surface energy calculations."""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass, field
from pathlib import Path

from jobflow import Flow, job
from pymatgen.core import Structure

from atomate2.siesta.flows.base import BaseSiestaFlowMaker
from atomate2.siesta.jobs.core import RelaxMaker, StaticMaker
from atomate2.siesta.jobs.surface.core import (
    calculate_surface_energies,
    plot_surface_energies,
    write_surface_energy_summary,
)

logger = logging.getLogger(__name__)


@dataclass
class SurfaceEnergyFlowMaker(BaseSiestaFlowMaker):
    """
    Calculate surface energies for all terminations of a given Miller index.

    This workflow:

    1. Calculates bulk energy (once)
    2. Reads all slab terminations from a directory
    3. Calculates slab energies (optionally with relaxation)
    4. Computes surface energies for each termination
    5. Generates plots and summary

    Inherits from BaseSiestaFlowMaker, so dry_run=True automatically propagates
    to child makers (bulk_static_maker, slab_static_maker, slab_relax_maker).

    Parameters
    ----------
    name : str
        Name of the flow.
    slab_directory : str | Path
        Directory containing slab files generated by generate_slabs_refactored.py.
        Should contain .fdf/.xsf files and \\*_validation.json metadata files.
    bulk_static_maker : StaticMaker
        Maker for bulk energy calculation.
    slab_static_maker : StaticMaker
        Maker for slab energy calculations.
    slab_relax_maker : RelaxMaker, optional
        Maker for slab relaxation before energy calculation. If None, slabs are rigid.
    miller_indices : tuple[int, int, int]
        Miller indices (h, k, l) of the surface.
    formula_units_per_cell : int, optional
        Number of formula units in bulk unit cell. Auto-detected if None.
    plot_results : bool
        Whether to generate surface energy plots.
    write_summary : bool
        Whether to write text summary file.
    dry_run : bool
        If True, skip SIESTA calculations and only save structures (inherited).
    dry_run_output_dir : str
        Directory to save dry-run structures (inherited).
    dry_run_format : str
        Output format for dry-run structures (inherited).

    Examples
    --------
    >>> from pymatgen.core import Structure
    >>> from atomate2.siesta.flows.surface import SurfaceEnergyFlowMaker
    >>> from atomate2.siesta.jobs.core import StaticMaker
    >>> from atomate2.siesta.sets.core import StaticSetGenerator
    >>>
    >>> # Setup SIESTA parameters
    >>> bulk_params = {
    ...     "PAO.BasisSize": "DZP",
    ...     "Mesh.Cutoff": "300 Ry",
    ...     "kpts": [8, 8, 8],
    ... }
    >>> slab_params = {
    ...     "PAO.BasisSize": "DZP",
    ...     "Mesh.Cutoff": "300 Ry",
    ...     "kpts": [8, 8, 1],
    ... }
    >>>
    >>> bulk_maker = StaticMaker(
    ...     input_set_generator=StaticSetGenerator(user_params=bulk_params)
    ... )
    >>> slab_maker = StaticMaker(
    ...     input_set_generator=StaticSetGenerator(user_params=slab_params)
    ... )
    >>>
    >>> # Create workflow
    >>> bulk = Structure.from_file("MgO.cif")
    >>> maker = SurfaceEnergyFlowMaker(
    ...     slab_directory="slabs_001",
    ...     bulk_static_maker=bulk_maker,
    ...     slab_static_maker=slab_maker,
    ...     miller_indices=(0, 0, 1),
    ... )
    >>> flow = maker.make(bulk)
    """

    name: str = "surface_energy"
    slab_directory: str | Path = field(default=".")
    bulk_static_maker: StaticMaker = field(default_factory=StaticMaker)
    slab_static_maker: StaticMaker = field(default_factory=StaticMaker)
    slab_relax_maker: RelaxMaker | None = None
    miller_indices: tuple[int, int, int] = (0, 0, 1)
    formula_units_per_cell: int | None = None
    plot_results: bool = True
    write_summary: bool = True

    def make(self, structure: Structure, prev_dir: str | Path | None = None) -> Flow:
        """
        Create surface energy calculation workflow.

        Parameters
        ----------
        structure : Structure
            Bulk structure.
        prev_dir : str | Path, optional
            Previous directory for restart.

        Returns
        -------
        Flow
            Surface energy calculation flow.
        """
        from atomate2.siesta.utils.common import print_docstring_in_box

        print_docstring_in_box(self.__doc__, title=self.__class__.__name__)

        logger.info("SurfaceEnergyFlowMaker.make()")

        jobs = []

        # 1. Calculate bulk energy
        logger.info("Creating bulk energy calculation job...")
        bulk_job = self.bulk_static_maker.make(structure, prev_dir=prev_dir)
        jobs.append(bulk_job)

        # 2. Discover all slab terminations from directory
        logger.info(f"Discovering slabs from directory: {self.slab_directory}")
        slab_files = self._discover_slabs(self.slab_directory)
        logger.info(f"Found {len(slab_files)} slab terminations")

        # 3. Calculate slab energies
        slab_calc_jobs = []
        for slab_file, metadata in slab_files:
            termination = metadata.get("termination", "unknown")
            logger.info(f"Creating jobs for termination: {termination}")

            # Read slab structure
            slab_structure = Structure.from_file(slab_file)

            if self.slab_relax_maker:
                # Relax then static
                relax_job = self.slab_relax_maker.make(slab_structure)
                relax_job.name = f"{self.name}_relax_{termination}"

                static_job = self.slab_static_maker.make(
                    relax_job.output.structure, prev_dir=relax_job.output.dir_name
                )
                static_job.name = f"{self.name}_static_{termination}"

                jobs.extend([relax_job, static_job])
            else:
                # Just static
                static_job = self.slab_static_maker.make(slab_structure)
                static_job.name = f"{self.name}_static_{termination}"
                jobs.append(static_job)

            slab_calc_jobs.append(
                {
                    "termination": termination,
                    "static_job": static_job,
                    "slab_structure": (
                        relax_job.output.structure
                        if self.slab_relax_maker
                        else slab_structure
                    ),
                    "metadata": metadata,
                }
            )

        # 4. Post-process: Calculate surface energies
        logger.info("Creating surface energy analysis job...")
        surface_energy_job = self._create_analysis_job(
            bulk_job=bulk_job, structure=structure, slab_calc_jobs=slab_calc_jobs
        )
        jobs.append(surface_energy_job)

        # 5. Optional: Plotting and summary
        if self.plot_results:
            logger.info("Adding plotting job...")
            plot_job = plot_surface_energies(surface_doc=surface_energy_job.output)
            plot_job.name = f"{self.name}_plot"
            jobs.append(plot_job)

        if self.write_summary:
            logger.info("Adding summary writer job...")
            summary_job = write_surface_energy_summary(
                surface_doc=surface_energy_job.output
            )
            summary_job.name = f"{self.name}_summary"
            jobs.append(summary_job)

        return Flow(jobs, output=surface_energy_job.output, name=self.name)

    def _discover_slabs(self, slab_dir: str | Path) -> list[tuple[Path, dict]]:
        """
        Discover all slab files and their metadata from directory.

        Parameters
        ----------
        slab_dir : str | Path
            Directory containing slab files.

        Returns
        -------
        list[tuple[Path, dict]]
            List of (slab_file_path, metadata_dict) tuples.
        """
        slab_dir = Path(slab_dir)

        if not slab_dir.exists():
            raise FileNotFoundError(f"Slab directory not found: {slab_dir}")

        # Find all validation JSON files (exclude initial slab)
        validation_files = list(slab_dir.glob("*_validation.json"))
        validation_files = [
            f for f in validation_files if "initial" not in f.name.lower()
        ]

        if not validation_files:
            raise ValueError(f"No slab validation files found in {slab_dir}")

        slab_files = []

        for val_file in validation_files:
            # Read metadata
            with open(val_file) as f:
                metadata = json.load(f)

            # Find corresponding structure file (prefer .fdf, fallback to .xsf)
            base_name = val_file.stem.replace("_validation", "")
            fdf_file = slab_dir / f"{base_name}.fdf"
            xsf_file = slab_dir / f"{base_name}.xsf"

            if fdf_file.exists():
                struct_file = fdf_file
            elif xsf_file.exists():
                struct_file = xsf_file
            else:
                logger.warning(f"No structure file found for {base_name}, skipping...")
                continue

            slab_files.append((struct_file, metadata))

        logger.info(f"Discovered {len(slab_files)} slabs:")
        for struct_file, metadata in slab_files:
            term = metadata.get("termination", "unknown")
            logger.info(f"  - {term}: {struct_file.name}")

        return slab_files

    def _create_analysis_job(
        self, bulk_job, structure: Structure, slab_calc_jobs: list[dict]
    ):
        """
        Create the surface energy analysis job.

        This job collects all slab energies and calculates surface energies.

        Parameters
        ----------
        bulk_job : Job
            Bulk energy calculation job.
        structure : Structure
            Bulk structure.
        slab_calc_jobs : list[dict]
            List of slab calculation job dictionaries.

        Returns
        -------
        Job
            Surface energy analysis job.
        """

        @job(name=f"{self.name}_analysis")
        def analyze_surface_energies():
            """Collect slab data and calculate surface energies."""
            # Collect slab data
            slab_data = []
            for slab_dict in slab_calc_jobs:
                slab_data.append(
                    {
                        "termination": slab_dict["termination"],
                        "slab_energy": slab_dict["static_job"].output.output.energy,
                        "slab_structure": slab_dict["slab_structure"],
                        "metadata": slab_dict["metadata"],
                    }
                )

            # Calculate surface energies
            return calculate_surface_energies(
                bulk_energy=bulk_job.output.output.energy,
                bulk_structure=structure,
                slab_data=slab_data,
                miller_indices=self.miller_indices,
                formula_units_per_cell=self.formula_units_per_cell,
            )

        return analyze_surface_energies()
