from datetime import datetime
from tokenize import group
from typing import ClassVar, Dict, Tuple, Mapping, List
from pydantic import BaseModel, Field
from pydantic import validator
from itertools import groupby

from monty.json import MontyDecoder 
from monty.tempfile import ScratchDir

from pymatgen.core import Structure
from pymatgen.entries.computed_entries import ComputedStructureEntry
from pymatgen.analysis.defects.core import Defect
from pymatgen.analysis.defects.corrections import get_freysoldt_correction, get_freysoldt2d_correction
from pymatgen.analysis.defects.thermo import DefectEntry, DefectSiteFinder
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from atomate2 import SETTINGS

from atomate2.common.schemas.structure import StructureMetadata
from atomate2.cp2k.schemas.calc_types.utils import run_type, task_type
from atomate2.cp2k.schemas.calc_types.enums import CalcType, TaskType, RunType
from atomate2.cp2k.schemas.task import TaskDocument

class DefectDoc(StructureMetadata):
    """
    A document used to represent a single defect. e.g. a O vacancy with a -2 charge.
    This document can contain an arbitrary number of defect entries, originating from
    pairs (defect and bulk) of calculations. This document provides access to the "best"
    calculation of each run_type.
    """

    class Config:
        arbitrary_types_allowed = True

    property_name: ClassVar[str] = "defect"

    defect: Defect = Field(None, description="Pymatgen defect object for this defect doc")

    name: str = Field(None, description="Name of this defect as generated by the defect object")

    material_id: int = Field(None, description="Unique material ID for the bulk material") #TODO Change to MPID

    task_ids: List[int] = Field(
        None, description="All task ids used in creating this defect doc."
    )

    calc_types: Mapping[int, CalcType] = Field(  # type: ignore
        None,
        description="Calculation types for all the calculations that make up this material",
    )
    task_types: Mapping[int, TaskType] = Field(
        None,
        description="Task types for all the calculations that make up this material",
    )
    run_types: Mapping[int, RunType] = Field(
        None,
        description="Run types for all the calculations that make up this material",
    )

    tasks: Mapping[RunType, Tuple[TaskDocument, TaskDocument]] = Field(
        None, description="Task documents (defect task, bulk task) for the defect entry of RunType"
    )

    entries: Mapping[RunType, DefectEntry] = Field(
        None, description="Dictionary for tracking entries for CP2K calculations"
    )

    last_updated: datetime = Field(
        description="Timestamp for when this document was last updated",
        default_factory=datetime.utcnow,
    )

    created_at: datetime = Field(
        description="Timestamp for when this material document was first created",
        default_factory=datetime.utcnow,
    )

    metadata: Dict = Field(description="Metadata for this defect")

    # TODO How can monty serialization incorporate into pydantic? It seems like VASP MatDocs dont need this
    @validator("entries", pre=True)
    def decode(cls, entries):
        for e in entries:
            if isinstance(entries[e], dict):
                entries[e] = MontyDecoder().process_decoded({k: v for k, v in entries[e].items()})
        return entries

    def update(self, defect_task, bulk_task, dielectric, query='defect'):

        defect_task_doc = TaskDocument(**defect_task)
        bulk_task_doc = TaskDocument(**bulk_task)

        rt = defect_task_doc.run_type
        tt = defect_task_doc.task_type
        ct = defect_task_doc.calc_type

        # Metadata
        last_updated = max(dtsk.last_updated for dtsk, btsk in self.tasks.values()) if self.tasks else datetime.now()
        created_at = min(dtsk.last_updated for dtsk, btsk in self.tasks.values()) if self.tasks else datetime.now()

        if defect_task_doc.task_id in self.task_ids:
            return
        else:
            self.last_updated = last_updated
            self.created_at = created_at
            self.task_ids.append(defect_task_doc.task_id)

            def _run_type(x):
                return run_type(x[0]['input']['dft']).value

            def _compare(new, old):
                # TODO return kpoint density
                return new['nsites'] > old.nsites

            if defect_task_doc.run_type not in self.tasks or _compare(defect_task, self.tasks[rt][0]):
                self.run_types.update({defect_task_doc.task_id: rt})
                self.task_types.update({defect_task_doc.task_id: tt})
                self.calc_types.update({defect_task_doc.task_id: ct})
                entry = self.__class__.get_defect_entry_from_tasks(
                            defect_task=defect_task,
                            bulk_task=bulk_task,
                            dielectric=dielectric,
                            query=query
                        )
                self.entries[rt] = entry
                self.tasks[rt] = (defect_task_doc, bulk_task_doc)

    def update_all(self, tasks, query='defect'):
        for defect_task, bulk_task, dielectric in tasks:
            self.update(defect_task=defect_task, bulk_task=bulk_task, dielectric=dielectric, query=query)

    @classmethod
    def from_tasks(cls, tasks: List, query='defect', material_id=None):
        """
        The standard way to create this document.
        Args:
            tasks: A list of defect,bulk task pairs which will be used to construct a
                series of DefectEntry objects.
            query: How to retrieve the defect object stored in the task.
        """
        task_group = [TaskDocument(**defect_task) for defect_task, bulk_task, dielectric in tasks]

        # Metadata
        last_updated = datetime.now() or max(task.last_updated for task in task_group)
        created_at = datetime.now() or min(task.completed_at for task in task_group)
        task_ids = {task.task_id for task in task_group}

        deprecated_tasks = list(
            {task.task_id for task in task_group if not task.is_valid}
        )

        run_types = {task.task_id: task.run_type for task in task_group}
        task_types = {task.task_id: task.task_type for task in task_group}
        calc_types = {task.task_id: task.calc_type for task in task_group}

        def _run_type(x):
            return run_type(x[0]['input']['dft']).value

        def _task_type(x):
            return task_type(x[0]['input']['dft']).value

        def _sort(x):
            # TODO return kpoint density, currently just does supercell size
            return -x[0]['nsites'], x[0]['output']['energy']

        entries = {}
        final_tasks = {}
        metadata = {}
        for key, tasks_for_runtype in groupby(sorted(tasks, key=_run_type), key=_run_type):
            sorted_tasks = sorted(tasks_for_runtype, key=_sort)
            ents = [cls.get_defect_entry_from_tasks(t[0], t[1], t[2], query) for t in sorted_tasks]
            best_entry = ents[0]
            best_defect_task, best_bulk_task, dielectric = sorted_tasks[0]
            metadata[key] = {'convergence': [(sorted_tasks[i][0]['nsites'], ents[i].energy) for i in range(len(ents))]}
            best_defect_task, best_bulk_task = TaskDocument(**best_defect_task), TaskDocument(**best_bulk_task)
            entries[best_defect_task.run_type] = best_entry
            final_tasks[best_defect_task.run_type] = (best_defect_task, best_bulk_task)

        data = {
                'entries': entries,
                'run_types': run_types,
                'task_types': task_types,
                'calc_types': calc_types,
                'last_updated': last_updated,
                'created_at': created_at,
                'task_ids': task_ids,
                'deprecated_tasks': deprecated_tasks,
                'tasks': final_tasks,
                'material_id': material_id if material_id else best_entry.parameters['material_id'],
                'entry_ids': {rt: entries[rt].entry_id for rt in entries},
                'defect': best_entry.defect,
                'name': best_entry.defect.name,
                'metadata': metadata,
        }
        prim = SpacegroupAnalyzer(best_entry.defect.bulk_structure).get_primitive_standard_structure()
        data.update(StructureMetadata.from_structure(prim).dict())
        return cls(**data)

    @classmethod
    def get_defect_entry_from_tasks(cls, defect_task, bulk_task, dielectric=None, query='transformations.history.0.defect'):
        """
        Extract a defect entry from a single pair (defect and bulk) of tasks.

        Args:
            defect_task: task dict for the defect calculation
            bulk_task: task dict for the bulk calculation
            dielectric: Dielectric doc if the defect is charged. If not present, no dielectric
                corrections will be performed, even if the defect is charged.
            query: Mongo-style query to retrieve the defect object from the defect task
        """
        parameters = cls.get_parameters_from_tasks(defect_task=defect_task, bulk_task=bulk_task)
        if dielectric:
            parameters['dielectric'] = dielectric

        corrections, metadata = cls.get_correction_from_parameters(parameters)

        sc_entry = ComputedStructureEntry(
            structure=parameters['final_defect_structure'], 
            energy=parameters['defect_energy'] - parameters['bulk_energy']
            )

        defect_entry = DefectEntry(
            defect=cls.get_defect_from_task(query=query, task=defect_task),
            charge_state=parameters['charge_state'],
            sc_entry=sc_entry,
            sc_defect_frac_coords=parameters['defect_frac_sc_coords'],
            corrections=corrections,
        )

        return defect_entry.as_dict()

    @classmethod
    def get_correction_from_parameters(cls, parameters) -> Tuple[Dict, Dict]:
        corrections = {}
        metadata = {}
        for correction in ["get_freysoldt_correction", "get_freysoldt2d_correction"]:
            c, m = getattr(cls, correction)(parameters)
            corrections.update(c)
            metadata.update(m)
        return corrections, metadata

    @classmethod
    def get_freysold_correction(cls, parameters) -> Tuple[Dict, Dict]:
        if parameters['charge_state'] and not parameters.get("2d"):
            return get_freysoldt_correction(
                q=parameters['charge_state'], dielectric=parameters['dielectric'], 
                defect_locpot=parameters['defect_v_hartree'], 
                bulk_locpot=parameters['bulk_v_hartree'], 
                defect_frac_coords=parameters['defect_frac_sc_coords'],
                )
        return {}, {}
    
    @classmethod
    def get_freysoldt2d_correction(cls, parameters):

        from pymatgen.io.vasp.outputs import VolumetricData as VaspVolumetricData

        if parameters['charge_state'] and parameters.get("2d"):
            eps_parallel = (parameters['dielectric'][0][0] + parameters['dielectric'][1][1]) / 2
            eps_perp = parameters['dielectric'][2][2]
            dielectric = (eps_parallel - 1) / (1 - 1/eps_perp)
            with ScratchDir('.'):
                
                lref = VaspVolumetricData(structure=parameters['bulk_locpot'].structure, data=parameters['bulk_locpot'].data)
                ldef = VaspVolumetricData(structure=parameters['defect_locpot'].structure, data=parameters['defect_locpot'].data)
                lref.write_file("LOCPOT.ref")
                ldef.write_file("LOCPOT.def")

                return get_freysoldt2d_correction(
                    q=parameters['charge_state'], dielectric=dielectric, defect_locpot="LOCPOT.def", 
                    bulk_locpot="LOCPOT.ref", defect_frac_coords=parameters['defect_frac_sc_coords'], 
                    energy_cutoff=250, slab_buffer=2
                    )
        return {}, {}

    @classmethod
    def get_defect_from_task(cls, query, task):
        """
        Unpack a Mongo-style query and retrieve a defect object from a task.
        """
        defect = unpack(query.split('.'), task)
        needed_keys = ['@module', '@class', 'structure', 'defect_site', 'charge', 'site_name']
        return MontyDecoder().process_decoded({k: v for k, v in defect.items() if k in needed_keys})

    @classmethod
    def get_parameters_from_tasks(cls, defect_task, bulk_task):
        """
        Get parameters necessary to create a defect entry from defect and bulk task dicts
        Args:
            defect_task: task dict for the defect calculation
            bulk_task: task dict for the bulk calculation
        """

        defect_task = TaskDocument(**defect_task)
        bulk_task = TaskDocument(**bulk_task)

        final_defect_structure = defect_task.structure
        final_bulk_structure = bulk_task.structure

        ghost = [index for index, prop in enumerate(final_defect_structure.site_properties.get("ghost")) if prop]
        if ghost:
            defect_frac_sc_coords = final_defect_structure[ghost[0]]
        else:
            defect_frac_sc_coords = DefectSiteFinder(SETTINGS.SYMPREC).get_defect_fpos(defect_structure=final_defect_structure, base_structure=final_bulk_structure)

        parameters = {
            'defect_energy': defect_task['output']['energy'],
            'bulk_energy': bulk_task['output']['energy'],
            'final_defect_structure': final_defect_structure,
            'vbm': bulk_task['output']['vbm'],
            'cbm': bulk_task['output']['cbm'],
            'charge_state': defect_task.output.structure.charge,
            'defect_frac_sc_coords': defect_frac_sc_coords,
            'defect_v_hartree': defect_task.cp2k_objects['v_hartree'], # TODO CP2K spec name
            'bulk_v_hartree': bulk_task.cp2k_objects['v_hartree'], # TODO CP2K spec name
        }

        return parameters

def unpack(query, d):
    if not query:
        return d
    if isinstance(d, List):
        return unpack(query[1:], d.__getitem__(int(query.pop(0))))
    return unpack(query[1:], d.__getitem__(query.pop(0)))