"""
Surface-aware defect generation for slab structures.

This module provides specialized defect generators that understand surface
vs bulk atoms in slab geometries. Critical for catalysis, adsorption, and
surface chemistry calculations.

Key Features:
- Automatic surface layer identification by z-coordinate
- Top/bottom/both surface selection
- Multiple surface layer support (e.g., top 2 layers)
- In-plane symmetry reduction (2D, not 3D)
- Subsurface defect generation
- Integration with existing SIESTA defect workflows

Example Use Cases:
- Oxygen vacancy on TiO2 (110) surface
- Sulfur vacancy on MoS₂ surface for catalysis
- Dopant substitution in topmost surface layer
- Subsurface interstitial for diffusion studies
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from typing import TYPE_CHECKING

import numpy as np

from atomate2.siesta.flows.defects.generation.vacancy import create_vacancy_with_ghost

if TYPE_CHECKING:
    from pymatgen.core import Structure

logger = logging.getLogger(__name__)


@dataclass
class LayerInfo:
    """
    Information about a structural layer in a slab.

    Attributes
    ----------
    layer_index : int
        Layer index (0 = bottommost, N-1 = topmost)
    z_position : float
        Average z-coordinate of atoms in this layer (Cartesian, Angstroms)
    atom_indices : list[int]
        Indices of atoms in this layer
    species_count : dict[str, int]
        Count of each species in this layer (e.g., {"Mo": 2, "S": 4})
    """

    layer_index: int
    z_position: float
    atom_indices: list[int]
    species_count: dict[str, int]


class SurfaceVacancyGenerator:
    """
    Generate vacancy defects specifically at surface sites in slab structures.

    This class automatically identifies surface layers by z-coordinate and
    generates defects only at surface atoms (not bulk-like interior atoms).
    Essential for surface chemistry, catalysis, and electrocatalysis studies.

    **Key Difference from SiestaVacancyGenerator**:
    - `SiestaVacancyGenerator`: Uses 3D symmetry, treats all atoms equally
    - `SurfaceVacancyGenerator`: Surface-aware, identifies top/bottom layers

    Parameters
    ----------
    slab_structure : Structure
        Slab structure (must be oriented with surface normal along z-axis).
        Typically generated by pymatgen's SlabGenerator or atomate2siesta's
        SurfaceMaker. Vacuum gap should be along z-direction.
    surface_layers : int
        Number of surface layers to include for defect generation.
        - 1: Only topmost layer (most common for surface defects)
        - 2: Top two layers (for subsurface effects)
        - 3+: Deeper layers (rare, for bulk-surface comparison)
        Default is 1 (topmost layer only).
    surface_side : str
        Which surface to generate defects on:
        - "top": Only top surface (most common)
        - "bottom": Only bottom surface (symmetric slabs)
        - "both": Both top and bottom surfaces (for symmetric slabs)
        Default is "top".
    layer_tolerance : float
        Z-coordinate tolerance for grouping atoms into layers (Angstroms).
        Atoms within this tolerance are considered in the same layer.
        Default is 0.7 Å (suitable for layered materials like MoS₂).
        Increase for highly corrugated surfaces or reconstructions.
        For simple surfaces, 0.5 Å may be sufficient.
    use_ghost_atoms : bool
        If True, replace removed atoms with ghost atoms (SIESTA-specific).
        If False, completely remove atoms (not recommended for SIESTA).
        Default is True.
    use_in_plane_symmetry : bool
        If True, use in-plane (2D) symmetry to reduce defect sites.
        This is different from 3D bulk symmetry - it only considers
        symmetry operations that preserve the z-coordinate (in-plane).
        Default is True (recommended to reduce calculations).
    symprec : float
        Symmetry tolerance for finding equivalent sites (Angstroms).
        Only used if use_in_plane_symmetry=True.
        Default is 0.1 Å.

    Examples
    --------
    **Example 1: Surface vacancy on MoS₂ (top layer only)**

    >>> from pymatgen.core import Structure
    >>> from atomate2.siesta.flows.defects.generation import SurfaceVacancyGenerator
    >>> mos2_slab = Structure.from_file("MoS2_slab.cif")
    >>>
    >>> # Generate S vacancies in topmost layer only
    >>> generator = SurfaceVacancyGenerator(
    ...     slab_structure=mos2_slab,
    ...     surface_layers=1,  # Top layer only
    ...     surface_side="top",
    ...     use_ghost_atoms=True,
    ... )
    >>>
    >>> # Get S vacancies
    >>> defects = generator.generate_defects(species="S")
    >>> print(f"Generated {len(defects)} surface S vacancy defects")

    **Example 2: Subsurface vacancies (top 2 layers)**

    >>> # Include subsurface layer for diffusion studies
    >>> generator = SurfaceVacancyGenerator(
    ...     slab_structure=tio2_slab,
    ...     surface_layers=2,  # Top two layers
    ...     surface_side="top",
    ... )
    >>>
    >>> # Generate O vacancies in surface + subsurface
    >>> defects = generator.generate_defects(species="O")
    >>> for defect in defects:
    ...     layer = defect["layer_index"]
    ...     z = defect["layer_z_position"]
    ...     print(f"V_O in layer {layer} (z={z:.2f} Å)")

    **Example 3: Both surfaces (symmetric slab)**

    >>> # Generate defects on both top and bottom surfaces
    >>> generator = SurfaceVacancyGenerator(
    ...     slab_structure=symmetric_slab,
    ...     surface_layers=1,
    ...     surface_side="both",  # Top AND bottom
    ... )
    >>>
    >>> defects = generator.generate_defects()
    >>> # Returns defects for both surfaces

    **Example 4: Multiple charge states with supercell**

    >>> generator = SurfaceVacancyGenerator(
    ...     slab_structure=mos2_slab, surface_layers=1, surface_side="top"
    ... )
    >>>
    >>> # Generate with 3×3×1 supercell (expand in-plane, not vertical)
    >>> defects = generator.generate_defects(
    ...     species="S",
    ...     supercell_matrix=[[3, 0, 0], [0, 3, 0], [0, 0, 1]],  # 3×3×1
    ...     charge_states=[0, +1, +2],
    ... )

    **Example 5: Disable in-plane symmetry (get ALL surface sites)**

    >>> # Useful for asymmetric surface sites (steps, kinks, etc.)
    >>> generator = SurfaceVacancyGenerator(
    ...     slab_structure=stepped_surface,
    ...     surface_layers=1,
    ...     surface_side="top",
    ...     use_in_plane_symmetry=False,  # All sites, no reduction
    ... )
    >>>
    >>> defects = generator.generate_defects(species="O")
    >>> # Returns vacancy at EVERY surface O atom

    Notes
    -----
    **Slab Orientation**:
    - Slab MUST be oriented with surface normal along z-axis
    - Vacuum gap should be along z-direction
    - Use pymatgen's SlabGenerator or atomate2siesta's SurfaceMaker
    - If slab is rotated, re-orient before using this generator

    **Layer Identification**:
    - Atoms grouped by z-coordinate within `layer_tolerance`
    - Works for flat surfaces and moderate corrugation
    - For highly reconstructed surfaces, increase `layer_tolerance`
    - Layers numbered from bottom (0) to top (N-1)

    **In-Plane Symmetry**:
    - Uses 2D symmetry operations that preserve z-coordinate
    - Different from bulk 3D symmetry (which mixes layers)
    - Reduces calculations by ~2-4× for common surfaces
    - Safe to disable for complex surface reconstructions

    **Supercells**:
    - For slabs, use in-plane expansion: [[n, 0, 0], [0, m, 0], [0, 0, 1]]
    - Do NOT expand in z-direction: [[n, 0, 0], [0, m, 0], [0, 0, k]]
    - Vacuum gap should remain unchanged
    - Typical: 3×3×1 or 4×4×1 for charged defects

    **Ghost Atoms**:
    - Highly recommended for SIESTA surface calculations
    - Maintains basis set coverage at vacancy sites
    - Critical for convergence of charged surface vacancies
    - Automatically handled by atomate2siesta's FDF generation

    See Also
    --------
    SiestaVacancyGenerator : General vacancy generator (bulk structures)
    create_vacancy_with_ghost : Low-level vacancy creation
    DefectFlowMaker : Workflow for defect formation energy calculations
    """  # noqa: RUF002

    def __init__(
        self,
        slab_structure: Structure,
        surface_layers: int = 1,
        surface_side: str = "top",
        layer_tolerance: float = 0.7,
        use_ghost_atoms: bool = True,
        use_in_plane_symmetry: bool = True,
        symprec: float = 0.1,
    ) -> None:
        """Initialize SurfaceVacancyGenerator."""
        self.slab_structure = slab_structure
        self.surface_layers = surface_layers
        self.surface_side = surface_side.lower()
        self.layer_tolerance = layer_tolerance
        self.use_ghost_atoms = use_ghost_atoms
        self.use_in_plane_symmetry = use_in_plane_symmetry
        self.symprec = symprec

        # Validate inputs
        if self.surface_side not in ["top", "bottom", "both"]:
            raise ValueError(
                f"surface_side must be 'top', 'bottom', or 'both', got '{surface_side}'"
            )

        if self.surface_layers < 1:
            raise ValueError(f"surface_layers must be >= 1, got {surface_layers}")

        # Identify layers in the slab
        self.layers = self._identify_layers()

        if len(self.layers) < self.surface_layers:
            logger.warning(
                f"Requested {self.surface_layers} surface layers, but slab "
                f"only has {len(self.layers)} layers total. Using all layers."
            )
            self.surface_layers = len(self.layers)

        # Log initialization
        logger.info(
            f"Initialized SurfaceVacancyGenerator for "
            f"{slab_structure.composition.reduced_formula}"
        )
        logger.info(f"  Total layers: {len(self.layers)}")
        logger.info(f"  Surface layers: {self.surface_layers}")
        logger.info(f"  Surface side: {self.surface_side}")
        logger.info(f"  Use ghost atoms: {use_ghost_atoms}")
        logger.info(f"  Use in-plane symmetry: {use_in_plane_symmetry}")

        # Log layer information
        for layer in self.layers:
            logger.debug(
                f"Layer {layer.layer_index}: z={layer.z_position:.3f} Å, "
                f"{len(layer.atom_indices)} atoms, species={layer.species_count}"
            )

    def _identify_layers(self) -> list[LayerInfo]:
        """
        Identify atomic layers in the slab by z-coordinate.

        Returns
        -------
        list[LayerInfo]
            List of LayerInfo objects, sorted from bottom to top.
        """
        # Get z-coordinates (Cartesian)
        z_coords = np.array([site.coords[2] for site in self.slab_structure])

        # Sort atoms by z-coordinate
        sorted_indices = np.argsort(z_coords)
        sorted_z = z_coords[sorted_indices]

        # Group atoms into layers based on tolerance
        layers: list[LayerInfo] = []
        current_layer_indices = [sorted_indices[0]]
        current_layer_z = sorted_z[0]

        for i in range(1, len(sorted_z)):
            z = sorted_z[i]
            idx = sorted_indices[i]

            # Check if this atom belongs to current layer
            if abs(z - current_layer_z) <= self.layer_tolerance:
                # Same layer
                current_layer_indices.append(idx)
            else:
                # New layer - save previous layer
                layer_info = self._create_layer_info(
                    layer_index=len(layers),
                    atom_indices=current_layer_indices,
                )
                layers.append(layer_info)

                # Start new layer
                current_layer_indices = [idx]
                current_layer_z = z

        # Add final layer
        if current_layer_indices:
            layer_info = self._create_layer_info(
                layer_index=len(layers),
                atom_indices=current_layer_indices,
            )
            layers.append(layer_info)

        logger.info(f"Identified {len(layers)} layers in slab")

        return layers

    def _create_layer_info(
        self, layer_index: int, atom_indices: list[int]
    ) -> LayerInfo:
        """Create LayerInfo object from atom indices."""
        # Calculate average z-coordinate
        z_coords = [self.slab_structure[i].coords[2] for i in atom_indices]
        avg_z = np.mean(z_coords)

        # Count species
        species_count: dict[str, int] = {}
        for idx in atom_indices:
            species = self.slab_structure[idx].specie.symbol
            species_count[species] = species_count.get(species, 0) + 1

        return LayerInfo(
            layer_index=layer_index,
            z_position=avg_z,
            atom_indices=atom_indices,
            species_count=species_count,
        )

    def get_surface_layers(self) -> list[LayerInfo]:
        """
        Get the surface layers for defect generation.

        Returns layers based on surface_side and surface_layers settings.

        Returns
        -------
        list[LayerInfo]
            Surface layers to generate defects in.
        """
        surface_layers = []

        # Top surface layers
        if self.surface_side in ["top", "both"]:
            # Get top N layers (highest z)
            top_layers = self.layers[-self.surface_layers :]
            surface_layers.extend(top_layers)

            logger.debug(
                f"Top surface: layers {[layer.layer_index for layer in top_layers]}"
            )

        # Bottom surface layers
        if self.surface_side in ["bottom", "both"]:
            # Get bottom N layers (lowest z)
            bottom_layers = self.layers[: self.surface_layers]
            surface_layers.extend(bottom_layers)

            logger.debug(
                f"Bottom surface: layers {[layer.layer_index for layer in bottom_layers]}"
            )

        return surface_layers

    def get_surface_sites(self, species: str | list[str] | None = None) -> list[dict]:
        """
        Get surface atom sites for defect generation.

        Applies in-plane symmetry reduction if enabled.

        Parameters
        ----------
        species : str or list[str], optional
            Filter by chemical species (e.g., "S" or ["Mo", "S"]).
            If None, include all species.

        Returns
        -------
        list[dict]
            List of site dictionaries, each containing:
            - site_index: Index in original structure
            - species: Chemical species
            - frac_coords: Fractional coordinates
            - layer_index: Which layer (0 = bottom, N-1 = top)
            - layer_z_position: Z-coordinate of layer (Cartesian, Å)
            - is_top_surface: Boolean (True if from top surface)
            - is_bottom_surface: Boolean (True if from bottom surface)
        """
        # Convert species to list
        if isinstance(species, str):
            species_list = [species]
        elif species is None:
            species_list = None
        else:
            species_list = species

        # Get surface layers
        surface_layers = self.get_surface_layers()

        # Collect all surface atoms
        surface_sites = []

        for layer in surface_layers:
            # Determine if this is top or bottom surface
            is_top = layer.layer_index >= len(self.layers) - self.surface_layers
            is_bottom = layer.layer_index < self.surface_layers

            for site_index in layer.atom_indices:
                site = self.slab_structure[site_index]
                site_species = site.specie.symbol

                # Filter by species if requested
                if species_list is not None and site_species not in species_list:
                    continue

                site_info = {
                    "site_index": site_index,
                    "species": site_species,
                    "frac_coords": site.frac_coords.tolist(),
                    "layer_index": layer.layer_index,
                    "layer_z_position": layer.z_position,
                    "is_top_surface": is_top,
                    "is_bottom_surface": is_bottom,
                }

                surface_sites.append(site_info)

        logger.info(
            f"Found {len(surface_sites)} surface sites for species {species_list}"
        )

        # Apply in-plane symmetry reduction if requested
        if self.use_in_plane_symmetry and len(surface_sites) > 0:
            surface_sites = self._apply_in_plane_symmetry(surface_sites)
            logger.info(
                f"After in-plane symmetry reduction: {len(surface_sites)} unique sites"
            )

        return surface_sites

    def _apply_in_plane_symmetry(self, sites: list[dict]) -> list[dict]:
        """
        Apply in-plane (2D) symmetry reduction to surface sites.

        This finds symmetry operations that preserve z-coordinate and
        reduces the list to symmetry-unique sites within each layer.

        Parameters
        ----------
        sites : list[dict]
            Surface sites to reduce

        Returns
        -------
        list[dict]
            Symmetry-reduced surface sites
        """
        # Group sites by layer
        sites_by_layer: dict[int, list[dict]] = {}
        for site in sites:
            layer_idx = site["layer_index"]
            if layer_idx not in sites_by_layer:
                sites_by_layer[layer_idx] = []
            sites_by_layer[layer_idx].append(site)

        # Apply symmetry within each layer independently
        unique_sites = []

        for layer_idx, layer_sites in sites_by_layer.items():
            # For in-plane symmetry, we need to analyze the 2D structure
            # For now, use a simple distance-based clustering approach
            # TODO: Implement proper 2D space group analysis

            # Simple approach: cluster sites by fractional x,y coordinates
            # and keep one representative per cluster

            clustered_sites: list[dict] = []
            for site in layer_sites:
                frac = np.array(site["frac_coords"])[:2]  # x, y only

                # Check if this site is equivalent to any clustered site
                is_equivalent = False
                for cluster_site in clustered_sites:
                    cluster_frac = np.array(cluster_site["frac_coords"])[:2]

                    # Check if within symmetry tolerance (in-plane only)
                    diff = np.abs(frac - cluster_frac)
                    # Handle periodic boundary
                    diff = np.minimum(diff, 1.0 - diff)

                    # Convert to Cartesian for distance check
                    lattice = self.slab_structure.lattice
                    cart_diff = lattice.get_cartesian_coords(np.append(diff, 0.0))[:2]
                    distance = np.linalg.norm(cart_diff)

                    if distance < self.symprec:
                        is_equivalent = True
                        break

                if not is_equivalent:
                    clustered_sites.append(site)

            unique_sites.extend(clustered_sites)

            logger.debug(
                f"Layer {layer_idx}: {len(layer_sites)} sites → "
                f"{len(clustered_sites)} unique sites"
            )

        return unique_sites

    def generate_defects(
        self,
        species: str | list[str] | None = None,
        supercell_matrix: list[list[int]] | None = None,
        charge_states: list[int] | None = None,
    ) -> list[dict]:
        """
        Generate surface vacancy defects.

        Parameters
        ----------
        species : str or list[str], optional
            Filter by chemical species (e.g., "S" or ["Mo", "S"]).
            If None, generate vacancies for all surface species.
        supercell_matrix : list[list[int]], optional
            Supercell transformation matrix (3×3).
            For slabs, use in-plane expansion: [[n,0,0], [0,m,0], [0,0,1]]
            Do NOT expand in z: [[n,0,0], [0,m,0], [0,0,k]] with k>1
            If None, use input structure without supercell.
        charge_states : list[int], optional
            List of charge states for each vacancy.
            If None, only generate neutral defects (q=0).
            Example: [0, +1, +2]

        Returns
        -------
        list[dict]
            List of defect dictionaries, each containing:
            - structure: Vacancy structure with ghost atom (if use_ghost_atoms=True)
            - host_structure: Pristine slab (same supercell as defect)
            - species: Species removed
            - site_index: Index of removed site
            - frac_coords: Fractional coordinates of vacancy
            - layer_index: Layer number (0 = bottom, N-1 = top)
            - layer_z_position: Z-coordinate of layer (Cartesian, Å)
            - is_top_surface: Boolean
            - is_bottom_surface: Boolean
            - charge_state: Charge state (0 if charge_states is None)
            - supercell_matrix: Supercell matrix used (or None)
            - defect_type: "surface_vacancy"
            - use_ghost: Boolean

        Examples
        --------
        >>> generator = SurfaceVacancyGenerator(mos2_slab, surface_layers=1)
        >>> defects = generator.generate_defects(species="S")
        >>> for defect in defects:
        ...     print(f"V_S at layer {defect['layer_index']}")
        """  # noqa: RUF002
        # Validate supercell for slabs
        if supercell_matrix is not None:
            sc_matrix = np.array(supercell_matrix)
            if sc_matrix[2, 2] != 1 or np.any(sc_matrix[2, :2] != 0):
                logger.warning(
                    "Supercell matrix expands in z-direction! "
                    "For slabs, use [[n,0,0],[0,m,0],[0,0,1]] to expand in-plane only. "
                    "Vacuum gap will be preserved."
                )

        # Get charge states
        if charge_states is None:
            charge_states = [0]

        # Get surface sites
        surface_sites = self.get_surface_sites(species=species)

        if len(surface_sites) == 0:
            logger.warning(f"No surface sites found for species {species}")
            return []

        # Generate defects
        defects = []

        for site_info in surface_sites:
            # Create base structure (with or without supercell)
            if supercell_matrix is not None:
                host_structure = self.slab_structure.copy()
                host_structure.make_supercell(supercell_matrix)

                # Find corresponding site index in supercell
                # For slabs, we only expand in-plane, so z-coordinate is preserved
                site_index_in_sc = None
                original_frac = np.array(site_info["frac_coords"])

                for i, site in enumerate(host_structure):
                    if site.specie.symbol == site_info["species"]:
                        sc_frac = site.frac_coords
                        sc_matrix = np.array(supercell_matrix)

                        # For slab (expanding in xy only), z is unchanged
                        # x, y are scaled by supercell matrix diagonal
                        if np.allclose(sc_matrix[2, :], [0, 0, 1]):
                            # In-plane expansion only
                            expected_sc_frac = original_frac.copy()
                            expected_sc_frac[0] /= sc_matrix[0, 0]
                            expected_sc_frac[1] /= sc_matrix[1, 1]
                            # z unchanged
                        else:
                            # General case (less common for slabs)
                            scaling = np.diag(sc_matrix)
                            expected_sc_frac = original_frac / scaling

                        frac_diff = np.abs(sc_frac - expected_sc_frac)
                        frac_diff = np.minimum(frac_diff, 1.0 - frac_diff)

                        if np.allclose(frac_diff, 0.0, atol=1e-3):
                            site_index_in_sc = i
                            break

                if site_index_in_sc is None:
                    logger.warning(
                        f"Could not find site {site_info['species']} at "
                        f"{site_info['frac_coords']} in supercell. "
                        f"Using first {site_info['species']} atom in that layer."
                    )
                    # Fallback: find first atom in same layer
                    layer_z = site_info["layer_z_position"]
                    for i, site in enumerate(host_structure):
                        if site.specie.symbol == site_info["species"]:
                            if abs(site.coords[2] - layer_z) < self.layer_tolerance:
                                site_index_in_sc = i
                                break

                if site_index_in_sc is None:
                    logger.error(f"Could not find {site_info['species']} in supercell!")
                    continue

                site_index = site_index_in_sc
                actual_frac_coords = host_structure[site_index].frac_coords.tolist()
            else:
                host_structure = self.slab_structure.copy()
                site_index = site_info["site_index"]
                actual_frac_coords = site_info["frac_coords"]

            # Create vacancy structure
            vacancy_structure = create_vacancy_with_ghost(
                structure=host_structure,
                site_index=site_index,
                use_ghost=self.use_ghost_atoms,
            )

            # Generate defect for each charge state
            for charge in charge_states:
                defect_info = {
                    "structure": vacancy_structure,
                    "host_structure": host_structure,
                    "species": site_info["species"],
                    "site_index": site_index,
                    "frac_coords": actual_frac_coords,
                    "layer_index": site_info["layer_index"],
                    "layer_z_position": site_info["layer_z_position"],
                    "is_top_surface": site_info["is_top_surface"],
                    "is_bottom_surface": site_info["is_bottom_surface"],
                    "charge_state": charge,
                    "supercell_matrix": supercell_matrix,
                    "defect_type": "surface_vacancy",
                    "use_ghost": self.use_ghost_atoms,
                }

                defects.append(defect_info)

                logger.debug(
                    f"Generated: V_{site_info['species']}^{charge:+d} "
                    f"in layer {site_info['layer_index']} "
                    f"(z={site_info['layer_z_position']:.2f} Å)"
                )

        logger.info(
            f"Generated {len(defects)} surface vacancy defect(s) "
            f"({len(surface_sites)} unique site(s) × {len(charge_states)} charge state(s))"  # noqa: RUF001
        )

        return defects
