"""Utilities for consistent text file output across atomate2siesta.

This module provides standardized headers, footers, and formatting for all
text file outputs generated by jobs, makers, and flows.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from typing import Any


def get_standard_header(
    title: str,
    width: int = 80,
    separator: str = "=",
) -> str:
    """
    Generate a standard header for text files.

    Parameters
    ----------
    title : str
        Title for the header
    width : int
        Width of the header (default: 80)
    separator : str
        Character to use for separator lines (default: "=")

    Returns
    -------
    str : Formatted header text
    """
    header = []
    header.append(separator * width)
    header.append(title)
    header.append(separator * width)
    header.append("")
    return "\n".join(header)


def get_standard_footer(
    width: int = 80,
    separator: str = "=",
    include_timestamp: bool = True,
    additional_info: dict[str, Any] | None = None,
) -> str:
    """
    Generate a standard footer for text files.

    The footer includes:
    - Generation timestamp (optional)
    - Software version information
    - Project information
    - Citation information
    - Additional custom information (optional)

    Parameters
    ----------
    width : int
        Width of the footer (default: 80)
    separator : str
        Character to use for separator lines (default: "=")
    include_timestamp : bool
        Whether to include generation timestamp (default: True)
    additional_info : dict[str, Any] | None
        Additional information to include in footer

    Returns
    -------
    str : Formatted footer text
    """
    footer = []
    footer.append("\n" + separator * width)
    footer.append("GENERATION INFORMATION")
    footer.append(separator * width)
    footer.append("")

    # Timestamp
    if include_timestamp:
        timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
        footer.append(f"Generated: {timestamp}")

    # Version information
    try:
        import atomate2.siesta

        version = atomate2.siesta.__version__
        footer.append(f"atomate2siesta version: {version}")
    except Exception:
        footer.append("atomate2siesta version: unknown")

    # Additional information
    if additional_info:
        footer.append("")
        for key, value in additional_info.items():
            footer.append(f"{key}: {value}")

    # Software information
    footer.append("")
    footer.append("Software Information:")
    footer.append("-" * width)
    footer.append("  atomate2siesta: SIESTA workflows for atomate2")
    footer.append("  https://github.com/materialsproject/atomate2")
    footer.append("")
    footer.append("  SIESTA: Spanish Initiative for Electronic Simulations with")
    footer.append("          Thousands of Atoms")
    footer.append("  https://departments.icmab.es/leem/siesta/")

    # Citation
    footer.append("")
    footer.append("Citation:")
    footer.append("-" * width)
    footer.append("  If you use this software in your research, please cite:")
    footer.append("")
    footer.append("  [1] Akhtar, A., Rignanese, G.-M., & Pruneda, J. M. (2026).")
    footer.append("      atomate2siesta: An Open-Source Framework for Automated DFT")
    footer.append("      Workflows with SIESTA.")
    footer.append("      https://github.com/materialsproject/atomate2")
    footer.append("")
    footer.append("  [2] J. M. Soler et al., J. Phys.: Condens. Matter 14, 2745 (2002)")
    footer.append("      DOI: 10.1088/0953-8984/14/11/302")
    footer.append("      (SIESTA method paper)")
    footer.append("")
    footer.append("  [3] A. García et al., J. Chem. Phys. 152, 204108 (2020)")
    footer.append("      DOI: 10.1063/5.0005077")
    footer.append("      (SIESTA recent developments)")

    footer.append("")
    footer.append(separator * width)

    return "\n".join(footer)


def get_section_header(
    title: str,
    width: int = 80,
    separator: str = "-",
) -> str:
    """
    Generate a section header for text files.

    Parameters
    ----------
    title : str
        Section title
    width : int
        Width of the header (default: 80)
    separator : str
        Character to use for separator line (default: "-")

    Returns
    -------
    str : Formatted section header
    """
    header = []
    header.append(title)
    header.append(separator * width)
    header.append("")
    return "\n".join(header)


class TextFileWriter:
    """
    Context manager for writing text files with consistent formatting.

    This class provides a convenient way to write text files with standard
    headers and footers.

    Parameters
    ----------
    filename : str
        Output filename
    title : str
        Title for the file header
    width : int
        Width of headers/footers (default: 80)
    include_timestamp : bool
        Whether to include timestamp in footer (default: True)
    additional_info : dict[str, Any] | None
        Additional information for footer

    Example
    -------
    >>> with TextFileWriter("results.txt", "Analysis Results") as f:
    ...     f.write("Result 1: 42\\n")
    ...     f.write("Result 2: 3.14\\n")
    """

    def __init__(
        self,
        filename: str,
        title: str,
        width: int = 80,
        include_timestamp: bool = True,
        additional_info: dict[str, Any] | None = None,
    ):
        """Initialize the TextFileWriter."""
        self.filename = filename
        self.title = title
        self.width = width
        self.include_timestamp = include_timestamp
        self.additional_info = additional_info
        self._file = None

    def __enter__(self):
        """Open file and write header."""
        self._file = open(self.filename, "w")
        header = get_standard_header(self.title, self.width)
        self._file.write(header)
        return self._file

    def __exit__(self, exc_type, exc_val, exc_tb):
        """Write footer and close file."""
        if self._file:
            footer = get_standard_footer(
                width=self.width,
                include_timestamp=self.include_timestamp,
                additional_info=self.additional_info,
            )
            self._file.write(footer)
            self._file.close()
        return False


def format_table(
    headers: list[str],
    rows: list[list[Any]],
    column_widths: list[int] | None = None,
    separator: str = "-",
) -> str:
    """
    Format data as an ASCII table.

    Parameters
    ----------
    headers : list[str]
        Column headers
    rows : list[list[Any]]
        Table rows (each row is a list of values)
    column_widths : list[int] | None
        Custom column widths (auto-calculated if None)
    separator : str
        Character for separator line (default: "-")

    Returns
    -------
    str : Formatted table as string

    Example
    -------
    >>> headers = ["Name", "Value", "Unit"]
    >>> rows = [
    ...     ["Energy", "42.5", "eV"],
    ...     ["Volume", "123.4", "Å³"],
    ... ]
    >>> print(format_table(headers, rows))
    Name     Value    Unit
    ------------------------
    Energy   42.5     eV
    Volume   123.4    Å³
    """
    if not column_widths:
        # Auto-calculate column widths
        column_widths = []
        for i, header in enumerate(headers):
            max_width = len(str(header))
            for row in rows:
                if i < len(row):
                    max_width = max(max_width, len(str(row[i])))
            column_widths.append(max_width + 2)  # Add padding

    # Format header
    header_line = "".join(
        str(h).ljust(w) for h, w in zip(headers, column_widths, strict=False)
    )
    separator_line = separator * len(header_line)

    # Format rows
    table_lines = [header_line, separator_line]
    for row in rows:
        row_line = "".join(
            str(v).ljust(w) for v, w in zip(row, column_widths, strict=False)
        )
        table_lines.append(row_line)

    return "\n".join(table_lines)


def format_key_value_pairs(
    data: dict[str, Any],
    key_width: int = 30,
    separator: str = ":",
) -> str:
    """
    Format dictionary as aligned key-value pairs.

    Parameters
    ----------
    data : dict[str, Any]
        Dictionary of key-value pairs
    key_width : int
        Width for key column (default: 30)
    separator : str
        Separator between key and value (default: ":")

    Returns
    -------
    str : Formatted key-value pairs

    Example
    -------
    >>> data = {"Energy": "42.5 eV", "Volume": "123.4 Å³"}
    >>> print(format_key_value_pairs(data))
    Energy:                       42.5 eV
    Volume:                       123.4 Å³
    """
    lines = []
    for key, value in data.items():
        formatted_key = f"{key}{separator}".ljust(key_width)
        lines.append(f"{formatted_key}{value}")
    return "\n".join(lines)
