Electrostatic site potentials (in V) using Ewald splitting parameter 3.14
This first parameter is a default value that was determined by LOBSTER

  atom#    atom      Potential       Potential
                    (Mulliken)       (Loewdin)
      1      Ba         -15.26          -15.09
      2      Ba         -15.26          -15.09
      3      Ba         -15.26          -15.09
      4      Ba         -15.26          -15.09
      5      Ba         -15.26          -15.09
      6      Ba         -15.26          -15.09
      7      Ba         -15.26          -15.09
      8      Ba         -15.26          -15.09
      9       O          14.82           14.78
     10       O          14.82           14.78
     11       F           8.25            8.14
     12       F           8.25            8.14
     13       F           8.59            8.48
     14       F           8.59            8.48
     15       F           8.25            8.14
     16       F           8.25            8.14
     17       F           8.25            8.14
     18       F           8.25            8.14
     19       F           8.59            8.48
     20       F           8.59            8.48
     21       F           8.25            8.14
     22       F           8.25            8.14

Madelung Energy (eV)   -174.01         -170.35
