#!/bin/bash -l

#SBATCH --nodes=4
#SBATCH --qos=debug
#SBATCH --time=00:30:00
#SBATCH --account=matgen
#SBATCH --job-name=4_cpu_debug
#SBATCH --output=4_cpu_debug-%j.out
#SBATCH --error=4_cpu_debug-%j.error
#SBATCH --constraint=cpu
#SBATCH --signal=SIGINT@60


module load python/3.9-anaconda-2021.11
#module load vasp/6.4.1-gpu #This version has OpenMP implementation 
module load vasp/6.3.2-cpu #Zhuoying uses this version but this doesnt have the OpenMP implementation
#module load vasp/6.3.2-gpu
#conda activate atomate2_10-22
conda activate atomate2_pheasy
module load cudatoolkit

#export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/global/homes/h/hrushi99/code/spglib_new2/spglib/lib64
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/global/homes/h/hrushi99/code/spglib_05-21/spglib/lib64
#export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/nvidia/hpc_sdk/Linux_x86_64/22.7/compilers/extras/qd/lib
#export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/nvidia/hpc_sdk/Linux_x86_64/22.7/compilers/lib

### Load Intel module
#module load PrgEnv-intel
#module load PrgEnv-gnu
# module load PrgEnv-nvidia

### Load cmake
module load cmake

#OpenMP settings:
export OMP_NUM_THREADS=16
export OMP_PLACES=threads
export OMP_PROC_BIND=spread

cd /pscratch/sd/h/hrushi99/atomate2/pheasy/block_2024-10-04-19-19-06-773297/launcher_2024-10-04-22-50-53-612670
rlaunch -w /global/homes/h/hrushi99/fw_config_perlmutter/cpu_reg/my_fworker.yaml rapidfire --nlaunches 1 --max_loops 3

# CommonAdapter (SLURM) completed writing Template
