#!/bin/bash -l
#SBATCH -J atomate2test
#SBATCH --nodes=2
#SBATCH --exclusive
#SBATCH --partition=big
#SBATCH --constraint=Infiniband,Gold6338
#SBATCH --ntasks=128
#SBATCH --time=24:00:00
#SBATCH --output=newmat.out.%j
#SBATCH --error=newmat.err.%j
#SBATCH --mail-user=aakash.naik@bam.de
#SBATCH --mail-type=ALL

source /software/BAM/VASP/oneAPI/setvars.sh intel64
# source /home/htc/anaik/env_pymatgen/bin/activate
source activate atomate2
# export PATH="/home/htc/anaik/bin/:$PATH"

cd /scratch/htc/anaik/anaik/Atomate2_test/block_2022-12-19-16-13-21-023386/launcher_2022-12-19-17-23-55-382403
rlaunch -c /home/htc/anaik/.fireworks/ singleshot --fw_id 22
