"""Tools for calculating elastic tensors."""

from __future__ import annotations

from typing import TYPE_CHECKING

import numpy as np

if TYPE_CHECKING:
    from collections.abc import Sequence

    from pymatgen.analysis.elasticity import Strain

# Number of strain states in the generic (triclinic) 3rd-order default set.
# Fitting a full 3rd-order expansion for an arbitrary symmetry needs this
# many independent strain states; see ``get_default_strain_states(order=3)``.
N_STRAIN_STATES_THIRD_ORDER = 14


def get_strain_state_summary(
    strains: Sequence[Strain], tol: float = 1e-10
) -> dict[tuple[int, ...], set[float]]:
    """
    Group strains into strain states and collect the magnitudes of each state.

    A "strain state" follows the convention used by pymatgen's
    finite-difference fitting (``pymatgen...elastic.get_strain_state_dict``):
    the tuple of Voigt indices with non-zero strain components. The magnitude
    of each strain within a state is taken from its first non-zero Voigt
    component.

    Parameters
    ----------
    strains : list of Strain
        Strains to analyze.
    tol : float
        Strain components with absolute value below this are treated as zero.

    Returns
    -------
    dict
        Mapping of strain state (tuple of Voigt indices) to the set of
        distinct magnitudes sampled for that state.
    """
    states: dict[tuple[int, ...], set[float]] = {}
    for strain in strains:
        voigt = np.asarray(strain.voigt, dtype=float)
        nonzero = tuple(np.nonzero(np.abs(voigt) > tol)[0].tolist())
        if not nonzero:
            continue  # zero strain (equilibrium state)
        states.setdefault(nonzero, set()).add(round(float(voigt[nonzero[0]]), 12))
    return states


def estimate_expansion_order(strains: Sequence[Strain], tol: float = 1e-10) -> int:
    """
    Estimate the elastic tensor expansion order supported by a set of strains.

    The decision is based on the structure of the data rather than the raw
    number of calculations. A 3rd-order (finite-difference) fit needs:

    - at least ``N_STRAIN_STATES_THIRD_ORDER`` (14) distinct strain states,
      including coupled states with more than one non-zero Voigt component,
      as generated by ``get_default_strain_states(order=3)``;
    - at least 3 distinct magnitudes per strain state, so that second
      derivatives of the stress can be evaluated.

    If any of these conditions is not met, a 2nd-order fit is returned.

    Parameters
    ----------
    strains : list of Strain
        Strains that were used in the deformation calculations.
    tol : float
        Strain components with absolute value below this are treated as zero.

    Returns
    -------
    int
        The estimated expansion order (2 or 3).
    """
    states = get_strain_state_summary(strains, tol=tol)
    if not states:
        return 2

    n_states = len(states)
    min_magnitudes = min(len(magnitudes) for magnitudes in states.values())
    has_coupled_states = any(len(state) > 1 for state in states)

    if (
        n_states >= N_STRAIN_STATES_THIRD_ORDER
        and min_magnitudes >= 3
        and has_coupled_states
    ):
        return 3
    return 2


def get_default_strain_states(order: int) -> list[tuple[int, int, int, int, int, int]]:
    """
    Generate a list of strain-states for calculating 2nd or 3rd order elastic tensors.

    Parameters
    ----------
    order : int
        Order of the tensor expansion to be calculated. Can be either 2 or 3.

    Returns
    -------
    list of tuple of int
        A list of strain states.
    """
    if order == 2:
        return [
            (1, 0, 0, 0, 0, 0),
            (0, 1, 0, 0, 0, 0),
            (0, 0, 1, 0, 0, 0),
            (0, 0, 0, 2, 0, 0),
            (0, 0, 0, 0, 2, 0),
            (0, 0, 0, 0, 0, 2),
        ]

    if order == 3:
        return [
            (1, 0, 0, 0, 0, 0),
            (0, 1, 0, 0, 0, 0),
            (0, 0, 1, 0, 0, 0),
            (0, 0, 0, 2, 0, 0),
            (0, 0, 0, 0, 2, 0),
            (0, 0, 0, 0, 0, 2),
            (1, 1, 0, 0, 0, 0),
            (1, 0, 1, 0, 0, 0),
            (1, 0, 0, 2, 0, 0),
            (1, 0, 0, 0, 2, 0),
            (0, 1, 1, 0, 0, 0),
            (0, 0, 0, 2, 2, 0),
            (0, 0, 0, 2, 0, 2),
            (0, 0, 0, 0, 2, 2),
        ]

    raise ValueError(
        "only deformations for 2nd and 3rd order elastic tensors are supported."
    )
