"""
Module defining base SIESTA input set and generator.

class Grids

Based on User's Guide Siesta 5.4.0
Section: 6.24 Output of charge densities and potentials on the grid
"""

# Metadata

__all__ = ["Grids"]

import logging
from dataclasses import dataclass, field, fields
from typing import Any

from atomate2.siesta.dataclass.base import FDFDataclass
from atomate2.siesta.utils.common import console
from atomate2.siesta.utils.verbosity import VerbosityLevel

logger = logging.getLogger(__name__)


@dataclass
class Grids(FDFDataclass):
    """
    Advanced grid output configuration for charge densities and potentials.

    This class manages the output of various charge densities, potentials, and
    grid-based quantities in SIESTA calculations. It provides control over which
    quantities are saved, in what format, and whether specialized analyses
    (like Bader charge analysis) should be performed.

    Parameters
    ----------
    save_rho : bool
        Save total electron charge density. Default: False
    save_delta_rho : bool
        Save deformation charge density (SCF - atomic). Default: False
    save_rho_xc : bool
        Save exchange-correlation potential on grid. Default: False
    save_electrostatic_potential : bool
        Save total electrostatic potential (Hartree + external). Default: False
    save_neutral_atom_potential : bool
        Save superposition of neutral-atom potentials. Default: False
    save_total_potential : bool
        Save total Kohn-Sham potential (electrostatic + XC). Default: False
    save_ionic_charge : bool
        Save ionic charge distribution. Default: False
    save_total_charge : bool
        Save total charge (electronic + ionic). Default: False
    save_grid_func_format : str
        File format for grid functions ("binary", "formatted", "netcdf").
        Default: "binary"
    save_bader_charge : bool
        Enable Bader charge analysis. Default: False
    analyze_charge_density_only : bool
        Only perform charge density analysis then stop. Default: False
    save_initial_charge_density : bool
        Save initial non-SCF charge density. Default: False

    Methods
    -------
    validate()
        Validate grid output configuration
    setup_advanced_grids(user_params)
        Create configured instance with fuzzy parameter matching
    """

    # Class-level verbosity control
    CONSOLE_VERBOSITY: VerbosityLevel = VerbosityLevel.ERROR

    # ----------------------------------------------------------
    # 6.24 Output of charge densities and potentials on the grid
    # ----------------------------------------------------------
    save_rho: bool = field(
        default=False,
        metadata={
            "description": (
                "Enables saving the total electron charge density to the grid."
            ),
            "SIESTA keyword": "SaveRho",
        },
    )

    save_delta_rho: bool = field(
        default=False,
        metadata={
            "description": (
                "Enables saving the deformation charge density "
                "(self-consistent minus atomic) to the grid."
            ),
            "SIESTA keyword": "SaveDeltaRho",
        },
    )

    save_rho_xc: bool = field(
        default=False,
        metadata={
            "description": (
                "Enables saving the exchange-correlation potential to the grid."
            ),
            "SIESTA keyword": "SaveRhoXC",
        },
    )

    save_electrostatic_potential: bool = field(
        default=False,
        metadata={
            "description": (
                "Enables saving the total electrostatic potential "
                "(Hartree + external) to the grid."
            ),
            "SIESTA keyword": "SaveElectrostaticPotential",
        },
    )

    save_neutral_atom_potential: bool = field(
        default=False,
        metadata={
            "description": (
                "Enables saving the potential generated by the superposition "
                "of neutral-atom potentials."
            ),
            "SIESTA keyword": "SaveNeutralAtomPotential",
        },
    )

    save_total_potential: bool = field(
        default=False,
        metadata={
            "description": (
                "Enables saving the total Kohn-Sham potential "
                "(electrostatic + XC) to the grid."
            ),
            "SIESTA keyword": "SaveTotalPotential",
        },
    )

    save_ionic_charge: bool = field(
        default=False,
        metadata={
            "description": (
                "Enables saving the ionic charge distribution (a set of delta "
                "functions at atomic positions) to the grid."
            ),
            "SIESTA keyword": "SaveIonicCharge",
        },
    )

    save_total_charge: bool = field(
        default=False,
        metadata={
            "description": (
                "Enables saving the total charge (electronic + ionic) to the grid."
            ),
            "SIESTA keyword": "SaveTotalCharge",
        },
    )

    save_grid_func_format: str = field(
        default="binary",
        metadata={
            "description": (
                "Sets the file format for saved grid functions. Options "
                "include 'binary', 'formatted', 'netcdf', etc."
            ),
            "SIESTA keyword": "SaveGridFunc.Format",
        },
    )

    save_bader_charge: bool = field(
        default=False,
        metadata={
            "description": (
                "A flag to enable Bader charge analysis, which requires saving "
                "the charge density."
            ),
            "SIESTA keyword": "SaveBaderCharge",
        },
    )

    analyze_charge_density_only: bool = field(
        default=False,
        metadata={
            "description": (
                "If true, the code will perform only a charge density analysis "
                "based on a previously read-in density matrix and then stop."
            ),
            "SIESTA keyword": "AnalyzeChargeDensityOnly",
        },
    )

    save_initial_charge_density: bool = field(
        default=False,
        metadata={
            "description": (
                "A flag to save the initial, non-self-consistent charge density "
                "at the beginning of the calculation."
            ),
            "SIESTA keyword": "SaveInitialChargeDensity",
        },
    )

    # Comment header for FDF output
    comments: str = field(
        default="# Grid Output Configuration (Grids dataclass module)",
        metadata={"description": "Comment header for FDF file"},
    )

    # Dictionary to hold FDF arguments
    grids_fdf_arguments: dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        """Register FDF parameters handled by this dataclass."""
        if not hasattr(self.__class__, "_registered"):
            self.register_fdf_params(
                "SaveRho",
                "SaveDeltaRho",
                "SaveRhoXC",
                "SaveElectrostaticPotential",
                "SaveNeutralAtomPotential",
                "SaveTotalPotential",
                "SaveIonicCharge",
                "SaveTotalCharge",
                "SaveGridFunc.Format",
                "SaveBaderCharge",
                "AnalyzeChargeDensityOnly",
                "SaveInitialChargeDensity",
                "SaveHS.NetCDF",
            )
            self.__class__._registered = True  # noqa: SLF001

    def validate(self) -> None:
        """
        Validate grid output options.

        Checks that grid output settings (charge densities, potentials, file formats)
        are properly configured for saving electronic structure data on real-space
        grids.

        Raises
        ------
        ValueError
            If grid output parameters are invalid or file format is unsupported
        """
        logger.info("Grids.validate()")

    def update_from_fdf(self, fdf_dict: dict[str, Any]) -> None:
        """
        Update this dataclass from FDF parameters.

        Args:
            fdf_dict: Dictionary of FDF parameters (from user_params)
        """
        for key, value in fdf_dict.items():
            key_lower = key.lower()

            # Boolean grid save flags
            if key_lower in ["saverho", "save_rho"]:
                self.save_rho = (
                    value.lower() in ["true", "t", "yes", "1"]
                    if isinstance(value, str)
                    else bool(value)
                )
            elif key_lower in ["savedeltarho", "save_delta_rho"]:
                self.save_delta_rho = (
                    value.lower() in ["true", "t", "yes", "1"]
                    if isinstance(value, str)
                    else bool(value)
                )
            elif key_lower in ["savegridfunc.format", "save_grid_func_format"]:
                self.save_grid_func_format = str(value)
            elif key_lower in ["savebadercharge", "save_bader_charge"]:
                self.save_bader_charge = (
                    value.lower() in ["true", "t", "yes", "1"]
                    if isinstance(value, str)
                    else bool(value)
                )

    def generate_fdf(self) -> dict[str, Any]:
        """
        Generate SIESTA FDF format parameters.

        Returns
        -------
            Dictionary of FDF parameters
        """
        fdf: dict[str, Any] = {}
        fdf["#Grids"] = "Grid Output Settings"

        if self.save_rho:
            fdf["SaveRho"] = "true"
        if self.save_delta_rho:
            fdf["SaveDeltaRho"] = "true"
        if self.save_rho_xc:
            fdf["SaveRhoXC"] = "true"
        if self.save_electrostatic_potential:
            fdf["SaveElectrostaticPotential"] = "true"
        if self.save_neutral_atom_potential:
            fdf["SaveNeutralAtomPotential"] = "true"
        if self.save_total_potential:
            fdf["SaveTotalPotential"] = "true"
        if self.save_ionic_charge:
            fdf["SaveIonicCharge"] = "true"
        if self.save_total_charge:
            fdf["SaveTotalCharge"] = "true"
        # Always write format when any grid save option is enabled
        any_grid_save = (
            self.save_rho
            or self.save_delta_rho
            or self.save_rho_xc
            or self.save_electrostatic_potential
            or self.save_neutral_atom_potential
            or self.save_total_potential
            or self.save_ionic_charge
            or self.save_total_charge
        )
        if any_grid_save:
            fdf["SaveGridFunc.Format"] = self.save_grid_func_format
        if self.save_bader_charge:
            fdf["SaveBaderCharge"] = "true"

        return fdf

    def to_ase(self) -> dict[str, Any]:
        """
        Generate ASE-format parameters.

        Returns
        -------
            Dictionary of ASE parameters
        """
        # ASE doesn't have grid output parameters
        # These are SIESTA-specific post-processing options
        return {}

    def generate_grid_block(self) -> None:
        """
        Generate FDF arguments for grid output with comment header.

        Populates grids_fdf_arguments dictionary with all grid output parameters
        that are set to non-default values. Adds comment header if comments are enabled.
        """
        logger.info("Grids.generate_grid_block()")

        # Collect parameters first (only non-default values)
        params_to_add = {}

        if self.save_rho:
            params_to_add["SaveRho"] = self.save_rho
        if self.save_delta_rho:
            params_to_add["SaveDeltaRho"] = self.save_delta_rho
        if self.save_rho_xc:
            params_to_add["SaveRhoXC"] = self.save_rho_xc
        if self.save_electrostatic_potential:
            params_to_add["SaveElectrostaticPotential"] = (
                self.save_electrostatic_potential
            )
        if self.save_neutral_atom_potential:
            params_to_add["SaveNeutralAtomPotential"] = self.save_neutral_atom_potential
        if self.save_total_potential:
            params_to_add["SaveTotalPotential"] = self.save_total_potential
        if self.save_ionic_charge:
            params_to_add["SaveIonicCharge"] = self.save_ionic_charge
        if self.save_total_charge:
            params_to_add["SaveTotalCharge"] = self.save_total_charge
        if self.save_grid_func_format != "binary":  # binary is default
            params_to_add["SaveGridFunc.Format"] = self.save_grid_func_format
        if self.save_bader_charge:
            params_to_add["SaveBaderCharge"] = self.save_bader_charge
        if self.analyze_charge_density_only:
            params_to_add["AnalyzeChargeDensityOnly"] = self.analyze_charge_density_only
        if self.save_initial_charge_density:
            params_to_add["SaveInitialChargeDensity"] = self.save_initial_charge_density

        # Only add comment header if there are parameters to add
        if params_to_add:
            if self.comments:
                self.grids_fdf_arguments["#Grids"] = self.comments
            self.grids_fdf_arguments.update(params_to_add)

    @classmethod
    def setup_advanced_grids(
        cls,
        user_params: dict[str, Any] | None = None,
        **kwargs,  # noqa: ARG003
    ) -> "Grids":
        """
        Create and configure a Grids instance with full parameter parsing.

        This method handles proper key normalization, type conversion, and fuzzy
        matching to configure grid output settings from user parameters. Supports
        SIESTA FDF parameter names (SaveRho, Save.DeltaRho, etc.) with automatic
        conversion.

        Args:
            user_params: Dictionary of user-defined parameters (case-insensitive,
                        may include dots).
                        If None or empty, all default values are used.
            **kwargs: Additional keyword arguments to override or supplement
                user_params.

        Returns
        -------
            Grids: Configured instance with all fields set.

        Examples
        --------
            >>> # Using SIESTA FDF parameter names
            >>> grids = Grids.setup_advanced_grids(
            ...     {
            ...         "SaveRho": True,
            ...         "SaveDeltaRho": True,
            ...         "SaveGridFunc.Format": "netcdf",
            ...     }
            ... )

            >>> # Using Python attribute names
            >>> grids = Grids.setup_advanced_grids(
            ...     {"save_rho": True, "save_bader_charge": True}
            ... )
        """
        if cls.CONSOLE_VERBOSITY.value >= VerbosityLevel.VERBOSE.value:
            console.print("[green]Grids.setup_advanced_grids()[/green]")

        # Initialize instance with defaults
        instance = cls()

        # Handle case where user_params is None or empty
        if user_params is None or not user_params:
            if cls.CONSOLE_VERBOSITY.value >= VerbosityLevel.DEBUG.value:
                console.print(
                    "[blue]No user parameters provided; "
                    "using all default Grids values.[/blue]"
                )
            return instance

        # Get valid attribute names (lowercase for comparison)
        grid_attributes = {
            field.name.lower()
            for field in fields(cls)
            if not field.name.startswith("_") and field.name != "CONSOLE_VERBOSITY"
        }
        if cls.CONSOLE_VERBOSITY.value >= VerbosityLevel.DEBUG.value:
            console.print(f"[blue]Available Grids attributes: {grid_attributes}[/blue]")

        # Process user parameters
        import re
        from difflib import get_close_matches

        for key, value in user_params.items():
            # Normalize key: handle camelCase and remove "save" prefix if repeated
            key_with_underscores = re.sub(r"([a-z])([A-Z])", r"\1_\2", key)
            key_normalized = key_with_underscores.replace(".", "_").lower()

            if cls.CONSOLE_VERBOSITY.value >= VerbosityLevel.DEBUG.value:
                console.print(
                    f"[blue]Processing key: {key} -> {key_normalized}, "
                    f"value: {value}[/blue]"
                )

            # Check if normalized key matches any attribute
            matched_attr = None
            if key_normalized in grid_attributes:
                matched_attr = key_normalized
            else:
                # Try fuzzy matching
                close_matches = get_close_matches(
                    key_normalized, grid_attributes, n=1, cutoff=0.6
                )
                if close_matches:
                    matched_attr = close_matches[0]
                    if cls.CONSOLE_VERBOSITY.value >= VerbosityLevel.VERBOSE.value:
                        console.print(
                            f"[yellow]Fuzzy match: '{key}' -> '{matched_attr}'[/yellow]"
                        )

            # Set attribute if matched
            if matched_attr:
                # Type conversion
                if matched_attr == "save_grid_func_format":
                    # String parameter - validate format
                    valid_formats = ["binary", "formatted", "netcdf", "cube"]
                    if isinstance(value, str):
                        if value.lower() in valid_formats:
                            setattr(instance, matched_attr, value.lower())
                        else:
                            console.print(
                                f"[yellow]Warning: '{value}' not in "
                                f"{valid_formats}. Using default.[/yellow]"
                            )
                    else:
                        setattr(instance, matched_attr, str(value))
                # Boolean parameters
                elif isinstance(value, bool):
                    setattr(instance, matched_attr, value)
                elif isinstance(value, str):
                    setattr(
                        instance,
                        matched_attr,
                        value.lower() in ["true", "t", "yes", "1"],
                    )
                else:
                    setattr(instance, matched_attr, bool(value))
            elif cls.CONSOLE_VERBOSITY.value >= VerbosityLevel.VERBOSE.value:
                console.print(
                    f"[yellow]Warning: No match found for parameter "
                    f"'{key}' in Grids[/yellow]"
                )

        # Generate FDF block with comment header
        instance.generate_grid_block()

        return instance
